
default: Doxyfile mainpage.h 
	doxygen Doxyfile
	@echo "******************************************************"
	@echo " Please load the doxygen documentation file           "
	@echo " "$(PWD)"/html/index.html"
	@echo " in your web browser    "	
	@echo "******************************************************"

clean:
	rm -rf html/
	rm -f *~
