CDI_reconstruction.c File Reference
#include <iostream>
#include <fstream>
#include <sstream>
#include <math.h>
#include <cstring>
#include <stdlib.h>
#include <fftw3.h>
#include <cstdlib>
#include <io.h>
#include <Complex_2D.h>
#include <Double_2D.h>
#include <BaseCDI.h>
#include <PlanarCDI.h>
#include <FresnelCDI.h>
#include <FresnelCDI_WF.h>
#include <PartialCDI.h>
#include <PolyCDI.h>
#include <Config.h>
Defines
#define OUTPUT_MINIMAL 0
#define OUTPUT_ITER 1
#define OUTPUT_ERROR 2
Functions
void print_usage ()
int main (int argc, char *argv[])
Variables
static const string planar_string = `planar`
static const string fresnel_string = `fresnel`
static const string fresnel_wf_string = `fresnel_wf`
static const string partial_string = `partial`
static const string poly_string = `poly`
Detailed Description
CDI_reconstruction.exe A tool for performing Planar, Fresnel or Partial Coherent (spatial and temporal) ESW reconstruction. This tool is provided as a demonstrative tool and to obtain results quickly.
Usage: CDI_reconstruction.exe <config filename> <reco_type> <seed>
where reco_type may be:
`planar` - planar
`fresnel_wf` - fresnel white-field reconstruction (3-plane propagation)
`fresnel` - fresnel object reconstruction. with the white-field previously reconstructed.
`partial` - partial spatial reconstruction.
`poly` - polychromatic or partially temporally coherent reconstruction.
The seed should be an integer. If the seed is excluded from the command line arguments, it is assumed to be `0`. If reco_type is also excluded, it is assumed to be `planar`.
Example:
CDI_reconstruction.exe planar_example.config "planar" 3 
 Perform planar CDI reconstruction using the configuration given in the file, `planar_example.config`. The random number generator (used to initial the first guess) is given a seed value of 3.
Definition in file CDI_reconstruction.c.
Function Documentation
int main (int argc, char * argv[])
Definition at line 90 of file CDI_reconstruction.c.
References BaseCDI::apply_shrinkwrap(), Complex_2D::clone(), FAILURE, fresnel_string, fresnel_wf_string, Complex_2D::get_2d(), BaseCDI::get_error(), Complex_2D::get_value(), BaseCDI::getAlgFromName(), Config::getDouble(), Config::getInt(), Config::getIntList(), Config::getStatus(), Config::getString(), Config::getStringList(), BaseCDI::initialise_estimate(), BaseCDI::iterate(), MAG, MAG_SQ, OUTPUT_ERROR, OUTPUT_MINIMAL, partial_string, planar_string, poly_string, print_usage(), BaseCDI::propagate_to_detector(), BaseCDI::set_algorithm(), BaseCDI::set_intensity(), and BaseCDI::set_support().