PartialCharCDI Class Reference
Public Member Functions
PartialCharCDI (Complex_2D &initial_guess, double z_dist=2, double beam_energy=1.239841e-6, double pixel_x_size=1, double pixel_y_size=1, unsigned int n_best=0)
void set_initial_coherence_guess (double lx_, double ly_)
void set_initial_coherence_guess_in_m (double lx_, double ly_)
virtual void initialise_estimate (int seed=0)
void set_intensity (const Double_2D &detector_intensity)
void set_minima_search_bounds_coefficient (double coef)
void set_minima_search_tolerance (double tol)
void set_minima_search_tolerance_in_m (double tol)
void set_minima_moving_average_weight (double w)
void set_minima_recalculation_interval (unsigned int ival)
double get_x_coherence_length ()
double get_y_coherence_length ()
double get_x_coherence_length_in_pixels ()
double get_y_coherence_length_in_pixels ()
virtual void propagate_to_detector (Complex_2D &c)
virtual void propagate_from_detector (Complex_2D &c)
void scale_intensity (Complex_2D &c)
virtual int iterate ()
Complex_2D * get_best_result (double &error, int index=0)
void set_support (const Double_2D &object_support, bool soften=false)
void set_beam_stop (const Double_2D &beam_stop_region)
void set_relaxation_parameter (double relaxation_parameter)
int get_size_x ()
int get_size_y ()
const Complex_2D & get_exit_surface_wave ()
void set_exit_surface_wave (Complex_2D &esw)
void set_algorithm (int alg)
void set_custom_algorithm (double m1, double m2, double m3, double m4, double m5, double m6, double m7, double m8, double m9, double m10)
void print_algorithm ()
double get_error ()
virtual void apply_shrinkwrap (double gauss_width=1.5, double threshold=0.1)
const Double_2D & get_support ()
virtual void apply_support (Complex_2D &c)
virtual void project_intensity (Complex_2D &c)
void set_fftw_type (int type)
virtual void set_complex_constraint (TransmissionConstraint &trans_constraint)
void reset_best ()
Static Public Member Functions
static int getAlgFromName (std::string algorithm_name)
Protected Member Functions
void apply_threshold (Double_2D &array, double threshold)
void convolve (Double_2D &array, double gauss_width, int pixel_cut_off=4)
void support_constraint (Complex_2D &c)
void reallocate_temp_complex_memory ()
void update_n_best ()
Static Protected Member Functions
static std::map< std::string, int > * set_up_algorithm_name_map ()
Protected Attributes
double lx
double ly
double z
double wavelength
double px_x_size
double px_y_size
Double_2D measured_intensity
Complex_2D & complex
int nx
int ny
Complex_2D * temp_complex_PFS
Complex_2D * temp_complex_PF
Complex_2D * temp_complex_PS
Complex_2D * temp_complex_PSF
double beta
Double_2D support
Double_2D intensity_sqrt
Double_2D * beam_stop
int algorithm
double algorithm_structure [NTERMS]
double current_error
int n_best
Complex_2D ** best_array
double * best_error_array
TransmissionConstraint * transmission_constraint
Static Protected Attributes
static std::map< std::string, int > * algNameMap = BaseCDI::set_up_algorithm_name_map()
Private Member Functions
Double_2D get_convoluted_intensity_estimate (Double_2D const &estimated_intensity, Double_2D const &measured_intensity)
Static Private Member Functions
static double convoluted_estimate_error (Double_2D const &measured_intensity, Double_2D const &estimated_intensity, double lx, double ly)
Private Attributes
unsigned int iteration
unsigned int minima_recalculation_interval
double minima_search_bounds_coefficient
double minima_search_tolerance
double minima_moving_average_weight
Detailed Description
Definition at line 32 of file PartialCharCDI.h.
Member Function Documentation
void set_initial_coherence_guess (double lx_, double ly_)
Default: 0.7, 0.7
Set an initial guess for the beam coherence lengths (in pixels).
Note that while bad values for this guess won't stop convergence, they can slow it down significantly.
Definition at line 47 of file PartialCharCDI.c++.
References lx, and ly.
void set_initial_coherence_guess_in_m (double lx_, double ly_)
Set an initial guess for the beam coherence lengths in m, measured in the object plane.
Definition at line 56 of file PartialCharCDI.c++.
References lx, ly, px_x_size, px_y_size, wavelength, and z.
void initialise_estimate (int seed = 0) [virtual]
Set the values in the Complex_2D to an initial estimate. For BaseCDI, this is set to random numbers inside the support for both the real and complex components, and zero outside the support.
Parameters:
seed The seed for the random number generator. By default this is 0.
Implements BaseCDI p..
Definition at line 160 of file PartialCharCDI.c++.
References BaseCDI::complex, IMAG, BaseCDI::intensity_sqrt, BaseCDI::nx, BaseCDI::ny, REAL, Complex_2D::set_value(), and BaseCDI::support.
void set_intensity (const Double_2D & detector_intensity)
Set the detector diffraction image (i.e. the square of the amplitude of the wavefield at the detector).
Parameters:
detector_intensity The intensity at the detector
Reimplemented from BaseCDI p..
Definition at line 185 of file PartialCharCDI.c++.
References BaseCDI::intensity_sqrt, measured_intensity, BaseCDI::nx, and BaseCDI::ny.
void set_minima_search_bounds_coefficient (double coef)
Default = 2.5
Set the factor that will be used to determine the search region. Search will go from 1/coef to coef times the current estimate.
If you are very unsure of your initial guess of lx and ly (beam coherence lengths) or if you are just using the default guess of 0.7 pixels in each direction, then you might want to increase this to 3.
Definition at line 71 of file PartialCharCDI.c++.
References minima_search_bounds_coefficient.
void set_minima_search_tolerance (double tol)
Default = 0.1
The the tolerance of the lx/ly minima search in pixels (search will terminate when uncertainty is less than this value).
Definition at line 80 of file PartialCharCDI.c++.
References minima_search_tolerance.
void set_minima_search_tolerance_in_m (double tol)
The the tolerance of the lx/ly minima search in object-plane-meters (search will terminate when uncertainty is less than this value).
Definition at line 88 of file PartialCharCDI.c++.
References minima_search_tolerance, px_x_size, px_y_size, wavelength, and z.
void set_minima_moving_average_weight (double w)
Default = 0.01
lx and ly values will be time averaged with the previous estimate (to smooth the slightly-erratic changes from iteration to iteration). w is the weight of the newly calculated value. The current estimate will be weighted at (1-w) to form a new current estimate. This is an exponential moving average.
Setting w to 1.0 will be the same as having no moving average.
Definition at line 104 of file PartialCharCDI.c++.
References minima_moving_average_weight.
void set_minima_recalculation_interval (unsigned int ival)
Default = 5
The values of lx and ly will only be updated every ival iterations (since the process is rather slow). There's not much advantage to doing this more frquently than the default of 5 unless there are very few total iterations being calculated.
Definition at line 115 of file PartialCharCDI.c++.
References minima_recalculation_interval.
double get_x_coherence_length ()
Retrieve the calculated coherence length of the beam (the std. deviation of the fitted gaussian) in the x direction, in meters, in the object plane.
Call this after iterating enough to produce a satisfactory image. This value will only be accurate to within the tolerances set by set_minima_search_tolerance_in_m.
Definition at line 126 of file PartialCharCDI.c++.
References lx, px_x_size, wavelength, and z.
double get_y_coherence_length ()
Retrieve the calculated coherence length of the beam (the std. deviation of the fitted gaussian) in the y direction, in meters, in the object plane.
Call this after iterating enough to produce a satisfactory image. This value will only be accurate to within the tolerances set by set_minima_search_tolerance_in_m.
Definition at line 137 of file PartialCharCDI.c++.
References ly, px_y_size, wavelength, and z.
double get_x_coherence_length_in_pixels ()
Retrieve the calculated x coherence length of the beam in pixels. This can be useful for interacting simulated data on a pixel-scale.
Definition at line 145 of file PartialCharCDI.c++.
References lx.
double get_y_coherence_length_in_pixels ()
Retrieve the calculated y coherence length of the beam in pixels. This can be useful for interacting simulated data on a pixel-scale.
Definition at line 154 of file PartialCharCDI.c++.
References ly.
void propagate_to_detector (Complex_2D & c) [virtual]
Propagate to the sample plane using a fast fourier transform.
Parameters:
c The Complex_2D field to propagate
Implements BaseCDI p..
Definition at line 196 of file PartialCharCDI.c++.
References Complex_2D::invert(), and Complex_2D::perform_forward_fft().
void propagate_from_detector (Complex_2D & c) [virtual]
Propagate to the detector plane using a fast fourier transform.
Parameters:
c The Complex_2D field to propagate
Implements BaseCDI p..
Definition at line 201 of file PartialCharCDI.c++.
References Complex_2D::invert(), and Complex_2D::perform_backward_fft().
void scale_intensity (Complex_2D & c) [virtual]
The intensity is scaled to match the measured data. The error is updated in this method.
Parameters:
c The complex field to apply the scaling to
Reimplemented from BaseCDI p..
Definition at line 209 of file PartialCharCDI.c++.
References BaseCDI::beam_stop, BaseCDI::current_error, Complex_2D::get_2d(), get_convoluted_intensity_estimate(), Complex_2D::get_mag(), BaseCDI::intensity_sqrt, iteration, lx, ly, MAG_SQ, measured_intensity, minima_recalculation_interval, BaseCDI::nx, BaseCDI::ny, and Complex_2D::set_mag().
Double_2D get_convoluted_intensity_estimate (Double_2D const & estimated_intensity, Double_2D const & measured_intensity) [private]
Find a gaussian matrix g with standard deviations in x and y that minimise the energy difference between the gaussian-convoluted current estimated intensity and the measured intensity. Returns the convolution of c and g (ie. the gaussian blurred estimate that best matches the measured intensity). This can be thought of as a coherence-corrected estimate.
See: Applied Physics Letters 99 (2011) - 'Simultaneous sample and spatial coherence characterisation using diffractive imaging' [doi: 10.1063/1.3650265] for further details.
Definition at line 261 of file PartialCharCDI.c++.
References lx, ly, measured_intensity, minima_moving_average_weight, minima_search_bounds_coefficient, and minima_search_tolerance.
double convoluted_estimate_error (Double_2D const & measured_intensity, Double_2D const & estimated_intensity, double lx, double ly) [static, private]
Take the integral over the absolute difference between the measured_intensity and the convolution of estimated_intesity and a gaussian of standard deviations lx and ly in x and y directions respectivley.
This is a measure for how accurate the estimate is given known coherence lengths lx and ly. It is used internally to automatically fit for lx and ly (by minimising its value in lx and ly) every few iterations.
This call is quite expensive.
Definition at line 288 of file PartialCharCDI.c++.
References measured_intensity.
int iterate () [virtual, inherited]
The main method for running the reconstruction! This method transforms the Complex_2D given to it according to:
$ x_{k+1} = g ( x_{k} ) $
 Where $g()$ depends on the algorithm used. The current error is also updated when this method is called.
Reimplemented in FresnelCDI_WF p., PartialCDI p., and PolyCDI p..
Definition at line 294 of file BaseCDI.c++.
References BaseCDI::algorithm, BaseCDI::algorithm_structure, BaseCDI::apply_support(), BaseCDI::complex, Complex_2D::copy(), Complex_2D::get_imag(), Complex_2D::get_real(), BaseCDI::nx, BaseCDI::ny, BaseCDI::project_intensity(), Complex_2D::set_imag(), Complex_2D::set_real(), SUCCESS, BaseCDI::temp_complex_PF, BaseCDI::temp_complex_PFS, BaseCDI::temp_complex_PS, BaseCDI::temp_complex_PSF, and BaseCDI::update_n_best().
Complex_2D * get_best_result (double & error, int index = 0) [inherited]
While the reconstruction is running this object will store the `n_best` number of best estimates according to the error metric. So, for example, if HIO is used and the error enters and leaves an error minima during reconstruction, the best (ie. lowest error) Complex_2D results will be kept. They can then be retrieved using this method.
Parameters:
index get best result number `index`. 0 is the best, 1 is the 2nd best etc...
error `error` is filled with the metric error of the selected best result
Definition at line 82 of file BaseCDI.c++.
References BaseCDI::best_array, BaseCDI::best_error_array, and BaseCDI::n_best.
void set_support (const Double_2D & object_support, bool soften = false) [inherited]
Set the sample support. A `0` value in the Double_2D is interpreted as being outside the support. Pixels with the maximum value of the Double_2D are considered inside the support. Values between 0 and the maximum indict the soft edge of the support. In this case, when the support is applied, the esw magnitude is scaled relative to the support edge value.
By default, the edge of a given support will be softened by convolution with a 3 pixel wide gaussian. This feature can be turned off by setting the boolean flag to false.
The support can be updated at anytime during reconstruction by calling this method.
Parameters:
object_support The sample support
soften If true, the edges of the support will be softened by covolving it with a 3 pixel wide gaussian. By default this option is off.
Definition at line 95 of file BaseCDI.c++.
References BaseCDI::convolve(), BaseCDI::nx, BaseCDI::ny, and BaseCDI::support.
void set_beam_stop (const Double_2D & beam_stop_region) [inherited]
Set the beam-stop position in the detector plane. This region will be leaf to float when the intensity if scaled during reconstruction. A zero in the array provided represents the beam stop and all other values represent the region which should be scaled.
Parameters:
beam_stop_region The region of the beam stop in the detector plane
Definition at line 109 of file BaseCDI.c++.
References BaseCDI::beam_stop, BaseCDI::nx, and BaseCDI::ny.
void set_relaxation_parameter (double relaxation_parameter) [inline, inherited]
Set the relaxation parameters of the reconstruction algorithm. This is $ \beta $ used exactly as it is in Harry's review paper. This maybe reset at anytime during the reconstruction by calling this method. The default value is 0.9.
Parameters:
relaxation_parameter The algorithm relaxation_parameter
Reimplemented in FresnelCDI_WF p..
Definition at line 261 of file BaseCDI.h.
References BaseCDI::algorithm, BaseCDI::beta, and BaseCDI::set_algorithm().
int get_size_x () [inline, inherited]
Returns: the number of pixel along the x-axis.
Definition at line 270 of file BaseCDI.h.
References BaseCDI::nx.
int get_size_y () [inline, inherited]
Returns: the number of pixel along the y-axis.
Definition at line 278 of file BaseCDI.h.
References BaseCDI::ny.
void set_algorithm (int alg) [inherited]
Set the algorithm. By default HIO is used.
Parameters:
alg The algorithm. The options are:
 ER - error reduction
 BIO - basic input-output
 BOO - basic output-output
 HIO - hybrid input-output
 DM - difference map
 SF - solvent-flipping
 ASR - averaged successive reflections
 HPR - hybrid projection reflection
 RAAR - relaxed averaged alternating reflectors
Reimplemented in FresnelCDI_WF p..
Definition at line 189 of file BaseCDI.c++.
References BaseCDI::algorithm, BaseCDI::beta, and BaseCDI::set_custom_algorithm().
void set_custom_algorithm (double m1, double m2, double m3, double m4, double m5, double m6, double m7, double m8, double m9, double m10) [inherited]
Iterative reconstruction algorithms can be expressed as a combination of the following 5 operators:
$ \hat{P}_S \hat{P}_F$, $\hat{P}_F \hat{P}_S$ , $ \hat{P}_S $ , $ \hat{P}_F $ and $ \hat{I} $
 Where $ \hat{P}_S $ is the support projection and $ \hat{P}_F $ is the intensity projection. These can be combined to form a basis of 10 vectors (see Harray's review). The parameters to this method set the coefficient for each of these vectors. Note: the vector set is linearly dependant.
Please see page 22 of the H.M. Quiney review: TUTORIAL REVIEW, Coherent diffractive imaging using short wavelength light sources, Journal of Modern Optics, 2010, DOI: 10.1080/09500340.2010.495459
Parameters:
m1 Coefficient to the $ [ \hat{P}_S \hat{P}_F - \hat{P}_F \hat{P}_S ]x_k $ term
m2 Coefficient to the $ [ \hat{P}_S \hat{P}_F - \hat{P}_F ]x_k $ term
m3 Coefficient to the $ [ \hat{P}_S \hat{P}_F - \hat{P}_S ]x_k $ term
m4 Coefficient to the $ [ \hat{P}_S \hat{P}_F - \hat{I} ]x_k $ term
m5 Coefficient to the $ [ \hat{P}_F \hat{P}_S - \hat{P}_F ]x_k $ term
m6 Coefficient to the $ [ \hat{P}_F \hat{P}_S - \hat{P}_S ]x_k $ term
m7 Coefficient to the $ [ \hat{P}_F \hat{P}_S - \hat{I} ]x_k $ term
m8 Coefficient to the $ [ \hat{P}_F - \hat{P}_S ]x_k $ term
m9 Coefficient to the $ [ \hat{P}_F - \hat{I} ]x_k $ term
m10 Coefficient to the $ [ \hat{P}_S - \hat{I} ]x_k $ term
Reimplemented in FresnelCDI_WF p..
Definition at line 237 of file BaseCDI.c++.
References BaseCDI::algorithm, BaseCDI::algorithm_structure, and BaseCDI::reallocate_temp_complex_memory().
void print_algorithm () [inherited]
Print the current algorithm to standard output. The algorithm is in the form:
 $ x_{k+1} = x_k + (a \hat{P}_S \hat{P}_F + b \hat{P}_F \hat{P}_S + c \hat{P}_S + d \hat{P}_F + e \hat{I} )x_k $
Reimplemented in FresnelCDI_WF p..
Definition at line 275 of file BaseCDI.c++.
References BaseCDI::algorithm, and BaseCDI::algorithm_structure.
double get_error () [inherited]
Get the difference between the estimated diffraction and the actual diffraction pattern.
 $ \chi^2 = \frac { \sum_{pixels} ( M_{pixel} - \sqrt{I_{pixel}} )^2 } { \sum_{pixels} {I_{pixel}} } $.
 Where $ M $ is the magnitude of the current estimate and $ I $ is the measured intensity.
NOTE: This method actually gives you the error for the previous iteration. This is because it's much faster to calculate the error during the intensity scaling step of the iteration rather than performing a FFT just for the error calculation.
Returns: The error metric
Definition at line 123 of file BaseCDI.c++.
References BaseCDI::current_error.
static int getAlgFromName (std::string algorithm_name) [inline, static, inherited]
Given the name of an algorithm, e.g. `HIO`, return the unique integer identifier. This is used by the configuration file reader, and probably won't be needed by users.
Parameters:
algorithm_name The algorithm name
Returns: The integer identifier
Definition at line 379 of file BaseCDI.h.
References BaseCDI::algNameMap.
void apply_shrinkwrap (double gauss_width = 1.5, double threshold = 0.1) [virtual, inherited]
Apply the shrinkwrap algorithm. The magnitude of the current ESW estimate will be convolved with a Gaussian, thresholded and set as the new support.
Parameters:
gauss_width The width ($ \sigma $) of the Gaussian in pixels. The default is 1.5.
threshold The threshold which is applied, as a fraction of the maximum pixel value. The default is 0.1 (10%).
Definition at line 413 of file BaseCDI.c++.
References BaseCDI::apply_threshold(), BaseCDI::complex, BaseCDI::convolve(), Complex_2D::get_2d(), MAG, BaseCDI::nx, BaseCDI::ny, and BaseCDI::set_support().
const Double_2D& get_support () [inline, inherited]
Get the current support. This might be useful if shrinkwrap has been applied, as it allows you to get the updated support.
Returns: An object reference to the current support.
Definition at line 405 of file BaseCDI.h.
References BaseCDI::support.
void apply_support (Complex_2D & c) [virtual, inherited]
Apply the support constraint.
Parameters:
c The complex field to apply the support constraint on
Reimplemented in FresnelCDI p..
Definition at line 127 of file BaseCDI.c++.
References TransmissionConstraint::apply_constraint(), BaseCDI::support_constraint(), and BaseCDI::transmission_constraint.
void project_intensity (Complex_2D & c) [virtual, inherited]
Apply the intensity constraint. The ESW is projected to the detector plane, the intensity is scaled to match the measured data and the field is projected back into the sample plane.
Parameters:
c The complex field to apply the intensity constraint on
Definition at line 153 of file BaseCDI.c++.
References BaseCDI::propagate_from_detector(), BaseCDI::propagate_to_detector(), and BaseCDI::scale_intensity().
void set_fftw_type (int type) [inherited]
A flag which is used for the fast fourier transforms to select the fft algorithm. It maybe either FFTW_ESTIMATE, FFTW_MEASURE or FFTW_PATIENT. See the fftw documentation for a description of each. By default we use FFTW_MEASURE. FFTW_ESTIMATE is used for testing purposes.
Parameters:
type - FFTW_ESTIMATE, FFTW_MEASURE or FFTW_PATIENT
Definition at line 491 of file BaseCDI.c++.
References BaseCDI::complex, Complex_2D::set_fftw_type(), BaseCDI::temp_complex_PF, and BaseCDI::temp_complex_PFS.
virtual void set_complex_constraint (TransmissionConstraint & trans_constraint) [inline, virtual, inherited]
void set_complex_constraint_function(void (*complex_constraint)(Complex_2D & tranmission)){ custom_complex_constraint = complex_constraint; }
Definition at line 468 of file BaseCDI.h.
References BaseCDI::transmission_constraint.
map< string, int > * set_up_algorithm_name_map () [static, protected, inherited]
Sets up the mapping between algorithm name and number. This is only called during the initialisation and should not be called elsewhere.
Returns: The algorithm name-iteger mapping
Definition at line 14 of file BaseCDI.c++.
void apply_threshold (Double_2D & array, double threshold) [protected, inherited]
Apply a threshold to the values in `array`.
Parameters:
array The array to be thresholded
threshold The threshold which is applied, as a fraction of the maximum pixel value. The default is 0.1 (10%).
Definition at line 474 of file BaseCDI.c++.
References BaseCDI::nx.
void convolve (Double_2D & array, double gauss_width, int pixel_cut_off = 4) [protected, inherited]
Convolved `array` with a 2-D Gaussian function. To speed up computation we only convolve up to 4 pixels away from the Gaussian peak.
Parameters:
array The array to be convolved
gauss_width The width ($ \sigma $) of the Gaussian in pixels. The default is 1.5.
pixel_cut_off Convolve up to 4 pixels away from the Gaussian peak.
Definition at line 429 of file BaseCDI.c++.
References BaseCDI::nx, and BaseCDI::ny.
Field Documentation
double lx [protected]
Last calculated coherence lengths.
Note: 'coherence length' is defined as the standard deviation of the coherence function in the DETECTOR-PLANE. This means that these are the fourier transform (ie. inverse since it's gaussian) of the coherence length in the object-plane.
Definition at line 71 of file PartialCharCDI.h.
Complex_2D& complex [protected, inherited]
a reference to the Complex_2D object which is altered during each iteration
Definition at line 91 of file BaseCDI.h.
int nx [protected, inherited]
The samplings in x
Definition at line 94 of file BaseCDI.h.
int ny [protected, inherited]
The samplings in y
Definition at line 97 of file BaseCDI.h.
Complex_2D* temp_complex_PFS [protected, inherited]
temporary Complex_2Ds which are used in the computation of the PFS and PF terms for each iteration.
Definition at line 105 of file BaseCDI.h.
double beta [protected, inherited]
the relaxation parameter
Reimplemented in PolyCDI p..
Definition at line 111 of file BaseCDI.h.
Double_2D support [protected, inherited]
a copy of the support
Definition at line 114 of file BaseCDI.h.
Double_2D intensity_sqrt [protected, inherited]
a copy of the square root of the intensity at the detector plane.
Definition at line 117 of file BaseCDI.h.
Double_2D* beam_stop [protected, inherited]
A mask of the beam-stop which is used when scaling the intensity
Definition at line 120 of file BaseCDI.h.
int algorithm [protected, inherited]
the algorithm which is being used: ER, HIO etc.
Definition at line 123 of file BaseCDI.h.
double algorithm_structure[NTERMS] [protected, inherited]
an array which holds the structure of the algorithm. i.e. the coefficients for each term in the iteration equation.
Definition at line 127 of file BaseCDI.h.
double current_error [protected, inherited]
the difference between the intensity in the detector plane the current estimated intensity.
Definition at line 131 of file BaseCDI.h.
int n_best [protected, inherited]
how many best estimates to store
Definition at line 134 of file BaseCDI.h.
Complex_2D** best_array [protected, inherited]
array of the best estimates
Definition at line 137 of file BaseCDI.h.
double* best_error_array [protected, inherited]
array of the error corresponding to each of the best estimates
Definition at line 141 of file BaseCDI.h.
TransmissionConstraint* transmission_constraint [protected, inherited]
a function pointer to a cumstomized complex constraint
Definition at line 145 of file BaseCDI.h.
map< string, int > * algNameMap = BaseCDI::set_up_algorithm_name_map() [static, protected, inherited]
a mapping between the algorithm name (string) and identification number
Definition at line 149 of file BaseCDI.h.
The documentation for this class was generated from the following files:
PartialCharCDI.h
PartialCharCDI.c++