FresnelCDI Class Reference
The class which performs Fresnel CDI reconstruction.
#include <FresnelCDI.h>
Public Member Functions
FresnelCDI (Complex_2D &initial_guess, Complex_2D &white_field, double beam_wavelength, double focal_detector_length, double focal_sample_length, double pixel_size, double normalisation=1.0, int n_best=0)
virtual ~FresnelCDI ()
virtual void initialise_estimate (int seed=0)
virtual void auto_set_norm ()
virtual void get_transmission_function (Complex_2D &result, Complex_2D *esw=0)
virtual void apply_support (Complex_2D &complex)
virtual void set_transmission_function (Complex_2D &transmission, Complex_2D *esw=0)
virtual void scale_intensity (Complex_2D &c)
virtual void propagate_from_detector (Complex_2D &c)
virtual void propagate_to_detector (Complex_2D &c)
void set_normalisation (double normalisation)
void set_experimental_parameters (double beam_wavelength, double focal_detector_length, double focal_sample_length, double pixel_size)
void set_norm (double new_normalisation)
const Complex_2D & get_illumination_at_sample ()
virtual int iterate ()
Complex_2D * get_best_result (double &error, int index=0)
void set_support (const Double_2D &object_support, bool soften=false)
void set_intensity (const Double_2D &detector_intensity)
void set_beam_stop (const Double_2D &beam_stop_region)
void set_relaxation_parameter (double relaxation_parameter)
int get_size_x ()
int get_size_y ()
const Complex_2D & get_exit_surface_wave ()
void set_exit_surface_wave (Complex_2D &esw)
void set_algorithm (int alg)
void set_custom_algorithm (double m1, double m2, double m3, double m4, double m5, double m6, double m7, double m8, double m9, double m10)
void print_algorithm ()
double get_error ()
virtual void apply_shrinkwrap (double gauss_width=1.5, double threshold=0.1)
const Double_2D & get_support ()
virtual void project_intensity (Complex_2D &c)
void set_fftw_type (int type)
virtual void set_complex_constraint (TransmissionConstraint &trans_constraint)
void reset_best ()
Static Public Member Functions
static int getAlgFromName (std::string algorithm_name)
Protected Member Functions
void multiply_factors (Complex_2D &c, int direction)
void check_illumination_at_sample ()
void apply_threshold (Double_2D &array, double threshold)
void convolve (Double_2D &array, double gauss_width, int pixel_cut_off=4)
void support_constraint (Complex_2D &c)
void reallocate_temp_complex_memory ()
void update_n_best ()
Static Protected Member Functions
static std::map< std::string, int > * set_up_algorithm_name_map ()
Protected Attributes
Complex_2D illumination
Complex_2D * illumination_at_sample
Complex_2D * transmission
double wavelength
double pixel_length
double focal_detector_length
double focal_sample_length
double norm
Complex_2D coefficient
Complex_2D & complex
int nx
int ny
Complex_2D * temp_complex_PFS
Complex_2D * temp_complex_PF
Complex_2D * temp_complex_PS
Complex_2D * temp_complex_PSF
double beta
Double_2D support
Double_2D intensity_sqrt
Double_2D * beam_stop
int algorithm
double algorithm_structure [NTERMS]
double current_error
int n_best
Complex_2D ** best_array
double * best_error_array
TransmissionConstraint * transmission_constraint
Static Protected Attributes
static std::map< std::string, int > * algNameMap = BaseCDI::set_up_algorithm_name_map()
Detailed Description
Author: Nadia Davidson <nadiamd@unimelb.edu.au>
The class used for performing Fresnel CDI reconstruction (for white-field reconstruction see FresnelCDI_WF). It inherits most methods from BaseCDI, so please look at the documentation of this class also. Although there are some differences in the underlying code between this class and the planar case, the interface is generally unchanged. Therefore users should refer to the instructions for BaseCDI to understand how to use a FresnelCDI object in their own code. Only the differences relevant to users will be documented here.
Definition at line 33 of file FresnelCDI.h.
Constructor & Destructor Documentation
FresnelCDI (Complex_2D & initial_guess, Complex_2D & white_field, double beam_wavelength, double focal_detector_length, double focal_sample_length, double pixel_size, double normalisation = 1.0, int n_best = 0)
Create a FresnelCDI object. All of the dimensions which are given as input should be in the same units. e.g metres.
Parameters:
initial_guess The complex 2-D field which is modified by this object. This represents the exit-surface-wave of the sample. It may be pre-initialised to a best first guess (e.g manually); it may be loaded from a file (e.g. the output from a previous reconstruction job); or it may be unitialised, and the default initialisation provided by FresnelCDI may be used.
white_field The reconstructed white-field (which has been previously determined using FresnelCDI_WF or otherwise)
beam_wavelength Wavelength of the beam
focal_detector_length The distance from the focal point to the detector
focal_sample_length The distance from the focal point to the sample
pixel_size The diameter of one of the detector pixels.
normalisation The amount to scale the data before subtracting the white field illumination. By default this is 1.0.
Definition at line 20 of file FresnelCDI.c++.
References Complex_2D::copy(), illumination, illumination_at_sample, norm, Complex_2D::scale(), BaseCDI::set_algorithm(), set_experimental_parameters(), and transmission.
~FresnelCDI () [virtual]
The destructor for this class
Definition at line 46 of file FresnelCDI.c++.
References illumination_at_sample, and transmission.
Member Function Documentation
void initialise_estimate (int seed = 0) [virtual]
Initialise the object esw (at the sample plane). The estimate is constructed by subtracting the white-field magnitude from the diffraction data. This forms the magnitude of the esw in the detector plane. The phase is set randomly and will lie within the range -0.1*2pi to 0.1*2pi. The esw is then propagated to the sample plane and the support is applied.
Parameters:
seed The seed of the random number generator
Double_2D temp(nx,ny); illumination_at_sample->get_2d(REAL,temp); double max = temp.get_max();
for(int i=0; i<nx; i++){ for(int j=0; j<ny; j++){ complex.set_phase(i,j,0.0); } }
make the magnitude the difference of the intensity and white-field double amp = intensity_sqrt.get(i,j)-illumination.get_mag(i,j);
perterb the phase a bit about zero to allow random starts. double phase = 0.2*2*M_PI*(0.5-rand()/((double) RAND_MAX)); complex.set_mag(i,j,amp); complex.set_phase(i,j,phase);
} }
take the result to the sample plane and apply the support propagate_from_detector(complex); apply_support(complex);
Implements BaseCDI p..
Definition at line 152 of file FresnelCDI.c++.
References apply_support(), BaseCDI::complex, BaseCDI::nx, BaseCDI::ny, Complex_2D::set_imag(), Complex_2D::set_real(), and set_transmission_function().
void get_transmission_function (Complex_2D & result, Complex_2D * esw = 0) [virtual]
Get the transmission function from the current estimate of the ESW. The ESW is divided by the illuminating wavefield in the sample plane and unity is added.
Parameters:
result The transmission function is copied into `result`.
Definition at line 298 of file FresnelCDI.c++.
References TransmissionConstraint::apply_constraint(), check_illumination_at_sample(), BaseCDI::complex, Complex_2D::get_imag(), Complex_2D::get_real(), illumination_at_sample, BaseCDI::nx, BaseCDI::ny, Complex_2D::set_imag(), Complex_2D::set_real(), and BaseCDI::transmission_constraint.
void apply_support (Complex_2D & complex) [virtual]
Apply the support constraint.
Parameters:
c The complex field to apply the support constraint on
Reimplemented from BaseCDI p..
Definition at line 203 of file FresnelCDI.c++.
References Complex_2D::Complex_2D(), get_transmission_function(), BaseCDI::nx, BaseCDI::ny, set_transmission_function(), BaseCDI::support_constraint(), transmission, and BaseCDI::transmission_constraint.
void set_transmission_function (Complex_2D & transmission, Complex_2D * esw = 0) [virtual]
Set the 'global' sample function. This method could be used, for example, instead of 'initialise_estimate' to initialise the results to those from a previous reconstruction.
Parameters:
new_transmission The transmission function exit-surface-wave to copy.
if(!illumination_at_sample){ illumination_at_sample = new Complex_2D(nx,ny); illumination_at_sample->copy(illumination); propagate_from_detector(*illumination_at_sample); }
Definition at line 253 of file FresnelCDI.c++.
References check_illumination_at_sample(), BaseCDI::complex, Complex_2D::get_imag(), Complex_2D::get_real(), illumination_at_sample, BaseCDI::nx, Complex_2D::set_imag(), Complex_2D::set_real(), and transmission.
void scale_intensity (Complex_2D & c) [virtual]
This method overrides the one in BaseCDI by adding/subtracting the white-field before/after applying the intensity constraint.
Parameters:
c The Complex_2D object to apply the intensity constraint on.
Reimplemented from BaseCDI p..
Definition at line 217 of file FresnelCDI.c++.
References Complex_2D::add(), illumination, and BaseCDI::scale_intensity().
void propagate_from_detector (Complex_2D & c) [virtual]
Propagate to the sample plane using the paraxial free-space equation.
Parameters:
c The Complex_2D field to propagate
Implements BaseCDI p..
Definition at line 238 of file FresnelCDI.c++.
References Complex_2D::invert(), multiply_factors(), and Complex_2D::perform_backward_fft().
void propagate_to_detector (Complex_2D & c) [virtual]
Propagate to the detector plane using the paraxial free-space equation.
Parameters:
c The Complex_2D field to propagate
Implements BaseCDI p..
Definition at line 245 of file FresnelCDI.c++.
References Complex_2D::invert(), multiply_factors(), and Complex_2D::perform_forward_fft().
void set_normalisation (double normalisation) [inline]
Reset the normalisation factor which is used to scale the white-field data.
Parameters:
normalisation The new normalisation
Definition at line 188 of file FresnelCDI.h.
References norm.
void set_experimental_parameters (double beam_wavelength, double focal_detector_length, double focal_sample_length, double pixel_size)
Reset the experimental parameters. This is called when an object of this type is constructed. I maybe called at any time during reconstruction, for example to refine the experimental parameters. This method resets the coefficient matricies which are used in the propagation between the detector and sample planes. All values should be given in the same length units.
Parameters:
beam_wavelength The beam wavelength
focal_detector_length The distance between the focal plane and dector plane.
focal_sample_length The distance between the focal plane and sample plane.
pixel_size The size of one detector pixel.
Definition at line 57 of file FresnelCDI.c++.
References coefficient, Complex_2D::Complex_2D(), Complex_2D::copy(), illumination, illumination_at_sample, BaseCDI::nx, BaseCDI::ny, pixel_length, propagate_from_detector(), Complex_2D::set_imag(), Complex_2D::set_real(), and wavelength.
void multiply_factors (Complex_2D & c, int direction) [protected]
double refine_sample_to_focal_length(double min=0, double max=0, int points_per_scan=8, double precision=0, int iterations_before_comparison=1, int crop_min_x=0, int crop_min_y=0, int crop_max_x=0, int crop_max_y=0);
Definition at line 98 of file FresnelCDI.c++.
References coefficient, Complex_2D::get_imag(), Complex_2D::get_real(), BaseCDI::nx, BaseCDI::ny, Complex_2D::set_imag(), and Complex_2D::set_real().
int iterate () [virtual, inherited]
The main method for running the reconstruction! This method transforms the Complex_2D given to it according to:
$ x_{k+1} = g ( x_{k} ) $
 Where $g()$ depends on the algorithm used. The current error is also updated when this method is called.
Reimplemented in FresnelCDI_WF p., PartialCDI p., and PolyCDI p..
Definition at line 294 of file BaseCDI.c++.
References BaseCDI::algorithm, BaseCDI::algorithm_structure, BaseCDI::apply_support(), BaseCDI::complex, Complex_2D::copy(), Complex_2D::get_imag(), Complex_2D::get_real(), BaseCDI::nx, BaseCDI::ny, BaseCDI::project_intensity(), Complex_2D::set_imag(), Complex_2D::set_real(), SUCCESS, BaseCDI::temp_complex_PF, BaseCDI::temp_complex_PFS, BaseCDI::temp_complex_PS, BaseCDI::temp_complex_PSF, and BaseCDI::update_n_best().
Complex_2D * get_best_result (double & error, int index = 0) [inherited]
While the reconstruction is running this object will store the `n_best` number of best estimates according to the error metric. So, for example, if HIO is used and the error enters and leaves an error minima during reconstruction, the best (ie. lowest error) Complex_2D results will be kept. They can then be retrieved using this method.
Parameters:
index get best result number `index`. 0 is the best, 1 is the 2nd best etc...
error `error` is filled with the metric error of the selected best result
Definition at line 82 of file BaseCDI.c++.
References BaseCDI::best_array, BaseCDI::best_error_array, and BaseCDI::n_best.
void set_support (const Double_2D & object_support, bool soften = false) [inherited]
Set the sample support. A `0` value in the Double_2D is interpreted as being outside the support. Pixels with the maximum value of the Double_2D are considered inside the support. Values between 0 and the maximum indict the soft edge of the support. In this case, when the support is applied, the esw magnitude is scaled relative to the support edge value.
By default, the edge of a given support will be softened by convolution with a 3 pixel wide gaussian. This feature can be turned off by setting the boolean flag to false.
The support can be updated at anytime during reconstruction by calling this method.
Parameters:
object_support The sample support
soften If true, the edges of the support will be softened by covolving it with a 3 pixel wide gaussian. By default this option is off.
Definition at line 95 of file BaseCDI.c++.
References BaseCDI::convolve(), BaseCDI::nx, BaseCDI::ny, and BaseCDI::support.
void set_intensity (const Double_2D & detector_intensity) [inherited]
Set the detector diffraction image (i.e. the square of the amplitude of the wavefield at the detector).
Parameters:
detector_intensity The intensity at the detector
Reimplemented in PartialCharCDI p..
Definition at line 115 of file BaseCDI.c++.
References BaseCDI::intensity_sqrt, BaseCDI::nx, and BaseCDI::ny.
void set_beam_stop (const Double_2D & beam_stop_region) [inherited]
Set the beam-stop position in the detector plane. This region will be leaf to float when the intensity if scaled during reconstruction. A zero in the array provided represents the beam stop and all other values represent the region which should be scaled.
Parameters:
beam_stop_region The region of the beam stop in the detector plane
Definition at line 109 of file BaseCDI.c++.
References BaseCDI::beam_stop, BaseCDI::nx, and BaseCDI::ny.
void set_relaxation_parameter (double relaxation_parameter) [inline, inherited]
Set the relaxation parameters of the reconstruction algorithm. This is $ \beta $ used exactly as it is in Harry's review paper. This maybe reset at anytime during the reconstruction by calling this method. The default value is 0.9.
Parameters:
relaxation_parameter The algorithm relaxation_parameter
Reimplemented in FresnelCDI_WF p..
Definition at line 261 of file BaseCDI.h.
References BaseCDI::algorithm, BaseCDI::beta, and BaseCDI::set_algorithm().
int get_size_x () [inline, inherited]
Returns: the number of pixel along the x-axis.
Definition at line 270 of file BaseCDI.h.
References BaseCDI::nx.
int get_size_y () [inline, inherited]
Returns: the number of pixel along the y-axis.
Definition at line 278 of file BaseCDI.h.
References BaseCDI::ny.
void set_algorithm (int alg) [inherited]
Set the algorithm. By default HIO is used.
Parameters:
alg The algorithm. The options are:
 ER - error reduction
 BIO - basic input-output
 BOO - basic output-output
 HIO - hybrid input-output
 DM - difference map
 SF - solvent-flipping
 ASR - averaged successive reflections
 HPR - hybrid projection reflection
 RAAR - relaxed averaged alternating reflectors
Reimplemented in FresnelCDI_WF p..
Definition at line 189 of file BaseCDI.c++.
References BaseCDI::algorithm, BaseCDI::beta, and BaseCDI::set_custom_algorithm().
void set_custom_algorithm (double m1, double m2, double m3, double m4, double m5, double m6, double m7, double m8, double m9, double m10) [inherited]
Iterative reconstruction algorithms can be expressed as a combination of the following 5 operators:
$ \hat{P}_S \hat{P}_F$, $\hat{P}_F \hat{P}_S$ , $ \hat{P}_S $ , $ \hat{P}_F $ and $ \hat{I} $
 Where $ \hat{P}_S $ is the support projection and $ \hat{P}_F $ is the intensity projection. These can be combined to form a basis of 10 vectors (see Harray's review). The parameters to this method set the coefficient for each of these vectors. Note: the vector set is linearly dependant.
Please see page 22 of the H.M. Quiney review: TUTORIAL REVIEW, Coherent diffractive imaging using short wavelength light sources, Journal of Modern Optics, 2010, DOI: 10.1080/09500340.2010.495459
Parameters:
m1 Coefficient to the $ [ \hat{P}_S \hat{P}_F - \hat{P}_F \hat{P}_S ]x_k $ term
m2 Coefficient to the $ [ \hat{P}_S \hat{P}_F - \hat{P}_F ]x_k $ term
m3 Coefficient to the $ [ \hat{P}_S \hat{P}_F - \hat{P}_S ]x_k $ term
m4 Coefficient to the $ [ \hat{P}_S \hat{P}_F - \hat{I} ]x_k $ term
m5 Coefficient to the $ [ \hat{P}_F \hat{P}_S - \hat{P}_F ]x_k $ term
m6 Coefficient to the $ [ \hat{P}_F \hat{P}_S - \hat{P}_S ]x_k $ term
m7 Coefficient to the $ [ \hat{P}_F \hat{P}_S - \hat{I} ]x_k $ term
m8 Coefficient to the $ [ \hat{P}_F - \hat{P}_S ]x_k $ term
m9 Coefficient to the $ [ \hat{P}_F - \hat{I} ]x_k $ term
m10 Coefficient to the $ [ \hat{P}_S - \hat{I} ]x_k $ term
Reimplemented in FresnelCDI_WF p..
Definition at line 237 of file BaseCDI.c++.
References BaseCDI::algorithm, BaseCDI::algorithm_structure, and BaseCDI::reallocate_temp_complex_memory().
void print_algorithm () [inherited]
Print the current algorithm to standard output. The algorithm is in the form:
 $ x_{k+1} = x_k + (a \hat{P}_S \hat{P}_F + b \hat{P}_F \hat{P}_S + c \hat{P}_S + d \hat{P}_F + e \hat{I} )x_k $
Reimplemented in FresnelCDI_WF p..
Definition at line 275 of file BaseCDI.c++.
References BaseCDI::algorithm, and BaseCDI::algorithm_structure.
double get_error () [inherited]
Get the difference between the estimated diffraction and the actual diffraction pattern.
 $ \chi^2 = \frac { \sum_{pixels} ( M_{pixel} - \sqrt{I_{pixel}} )^2 } { \sum_{pixels} {I_{pixel}} } $.
 Where $ M $ is the magnitude of the current estimate and $ I $ is the measured intensity.
NOTE: This method actually gives you the error for the previous iteration. This is because it's much faster to calculate the error during the intensity scaling step of the iteration rather than performing a FFT just for the error calculation.
Returns: The error metric
Definition at line 123 of file BaseCDI.c++.
References BaseCDI::current_error.
static int getAlgFromName (std::string algorithm_name) [inline, static, inherited]
Given the name of an algorithm, e.g. `HIO`, return the unique integer identifier. This is used by the configuration file reader, and probably won't be needed by users.
Parameters:
algorithm_name The algorithm name
Returns: The integer identifier
Definition at line 379 of file BaseCDI.h.
References BaseCDI::algNameMap.
void apply_shrinkwrap (double gauss_width = 1.5, double threshold = 0.1) [virtual, inherited]
Apply the shrinkwrap algorithm. The magnitude of the current ESW estimate will be convolved with a Gaussian, thresholded and set as the new support.
Parameters:
gauss_width The width ($ \sigma $) of the Gaussian in pixels. The default is 1.5.
threshold The threshold which is applied, as a fraction of the maximum pixel value. The default is 0.1 (10%).
Definition at line 413 of file BaseCDI.c++.
References BaseCDI::apply_threshold(), BaseCDI::complex, BaseCDI::convolve(), Complex_2D::get_2d(), MAG, BaseCDI::nx, BaseCDI::ny, and BaseCDI::set_support().
const Double_2D& get_support () [inline, inherited]
Get the current support. This might be useful if shrinkwrap has been applied, as it allows you to get the updated support.
Returns: An object reference to the current support.
Definition at line 405 of file BaseCDI.h.
References BaseCDI::support.
void project_intensity (Complex_2D & c) [virtual, inherited]
Apply the intensity constraint. The ESW is projected to the detector plane, the intensity is scaled to match the measured data and the field is projected back into the sample plane.
Parameters:
c The complex field to apply the intensity constraint on
Definition at line 153 of file BaseCDI.c++.
References BaseCDI::propagate_from_detector(), BaseCDI::propagate_to_detector(), and BaseCDI::scale_intensity().
void set_fftw_type (int type) [inherited]
A flag which is used for the fast fourier transforms to select the fft algorithm. It maybe either FFTW_ESTIMATE, FFTW_MEASURE or FFTW_PATIENT. See the fftw documentation for a description of each. By default we use FFTW_MEASURE. FFTW_ESTIMATE is used for testing purposes.
Parameters:
type - FFTW_ESTIMATE, FFTW_MEASURE or FFTW_PATIENT
Definition at line 491 of file BaseCDI.c++.
References BaseCDI::complex, Complex_2D::set_fftw_type(), BaseCDI::temp_complex_PF, and BaseCDI::temp_complex_PFS.
virtual void set_complex_constraint (TransmissionConstraint & trans_constraint) [inline, virtual, inherited]
void set_complex_constraint_function(void (*complex_constraint)(Complex_2D & tranmission)){ custom_complex_constraint = complex_constraint; }
Definition at line 468 of file BaseCDI.h.
References BaseCDI::transmission_constraint.
map< string, int > * set_up_algorithm_name_map () [static, protected, inherited]
Sets up the mapping between algorithm name and number. This is only called during the initialisation and should not be called elsewhere.
Returns: The algorithm name-iteger mapping
Definition at line 14 of file BaseCDI.c++.
void apply_threshold (Double_2D & array, double threshold) [protected, inherited]
Apply a threshold to the values in `array`.
Parameters:
array The array to be thresholded
threshold The threshold which is applied, as a fraction of the maximum pixel value. The default is 0.1 (10%).
Definition at line 474 of file BaseCDI.c++.
References BaseCDI::nx.
void convolve (Double_2D & array, double gauss_width, int pixel_cut_off = 4) [protected, inherited]
Convolved `array` with a 2-D Gaussian function. To speed up computation we only convolve up to 4 pixels away from the Gaussian peak.
Parameters:
array The array to be convolved
gauss_width The width ($ \sigma $) of the Gaussian in pixels. The default is 1.5.
pixel_cut_off Convolve up to 4 pixels away from the Gaussian peak.
Definition at line 429 of file BaseCDI.c++.
References BaseCDI::nx, and BaseCDI::ny.
Field Documentation
Complex_2D illumination [protected]
the reconstructed white field
Definition at line 38 of file FresnelCDI.h.
Complex_2D* illumination_at_sample [protected]
the white field in the sample plane
Definition at line 41 of file FresnelCDI.h.
Complex_2D* transmission [protected]
the transmission function
Definition at line 45 of file FresnelCDI.h.
double wavelength [protected]
the beam wavelength
Definition at line 48 of file FresnelCDI.h.
double pixel_length [protected]
the pixel size
Definition at line 51 of file FresnelCDI.h.
double norm [protected]
normalisation between the illumination with and without the sample placed in the beam
Definition at line 59 of file FresnelCDI.h.
Complex_2D coefficient [protected]
an array which holds a constants we use when propagating between difference planes
Definition at line 63 of file FresnelCDI.h.
Complex_2D& complex [protected, inherited]
a reference to the Complex_2D object which is altered during each iteration
Definition at line 91 of file BaseCDI.h.
int nx [protected, inherited]
The samplings in x
Definition at line 94 of file BaseCDI.h.
int ny [protected, inherited]
The samplings in y
Definition at line 97 of file BaseCDI.h.
Complex_2D* temp_complex_PFS [protected, inherited]
temporary Complex_2Ds which are used in the computation of the PFS and PF terms for each iteration.
Definition at line 105 of file BaseCDI.h.
double beta [protected, inherited]
the relaxation parameter
Reimplemented in PolyCDI p..
Definition at line 111 of file BaseCDI.h.
Double_2D support [protected, inherited]
a copy of the support
Definition at line 114 of file BaseCDI.h.
Double_2D intensity_sqrt [protected, inherited]
a copy of the square root of the intensity at the detector plane.
Definition at line 117 of file BaseCDI.h.
Double_2D* beam_stop [protected, inherited]
A mask of the beam-stop which is used when scaling the intensity
Definition at line 120 of file BaseCDI.h.
int algorithm [protected, inherited]
the algorithm which is being used: ER, HIO etc.
Definition at line 123 of file BaseCDI.h.
double algorithm_structure[NTERMS] [protected, inherited]
an array which holds the structure of the algorithm. i.e. the coefficients for each term in the iteration equation.
Definition at line 127 of file BaseCDI.h.
double current_error [protected, inherited]
the difference between the intensity in the detector plane the current estimated intensity.
Definition at line 131 of file BaseCDI.h.
int n_best [protected, inherited]
how many best estimates to store
Definition at line 134 of file BaseCDI.h.
Complex_2D** best_array [protected, inherited]
array of the best estimates
Definition at line 137 of file BaseCDI.h.
double* best_error_array [protected, inherited]
array of the error corresponding to each of the best estimates
Definition at line 141 of file BaseCDI.h.
TransmissionConstraint* transmission_constraint [protected, inherited]
a function pointer to a cumstomized complex constraint
Definition at line 145 of file BaseCDI.h.
map< string, int > * algNameMap = BaseCDI::set_up_algorithm_name_map() [static, protected, inherited]
a mapping between the algorithm name (string) and identification number
Definition at line 149 of file BaseCDI.h.
The documentation for this class was generated from the following files:
FresnelCDI.h
FresnelCDI.c++