Complex_2D Class Reference
A 2-dimensional array of complex numbers.
#include <Complex_2D.h>
Public Member Functions
Complex_2D (int x_size, int y_size)
~Complex_2D ()
Complex_2D (const Complex_2D &object)
Complex_2D & operator= (const Complex_2D &rhs)
void set_value (int x, int y, int type, double value)
void set_real (int x, int y, double value)
void set_imag (int x, int y, double value)
void set_mag (int x, int y, double value)
void set_phase (int x, int y, double value)
double get_real (int x, int y) const
double get_imag (int x, int y) const
double get_mag (int x, int y) const
double get_phase (int x, int y) const
double get_value (int x, int y, int type) const
int get_size_x () const
int get_size_y () const
void get_2d (int type, Double_2D &result) const
void scale (double scale_factor)
void add (Complex_2D &c2, double scale=1)
void multiply (Complex_2D &c2, double scale=1)
double get_norm () const
Complex_2D * clone () const
void copy (const Complex_2D &c)
void invert (bool scale=false)
void conjugate ()
void perform_forward_fft ()
void perform_backward_fft ()
void perform_backward_fft_real (Double_2D &result)
void perform_forward_fft_real (Double_2D &input)
void set_fftw_type (int type)
Complex_2D get_padded (int x_add, int y_add)
Complex_2D get_unpadded (int x_add, int y_add)
Private Member Functions
int check_bounds (int x, int y) const
void initialise_fft ()
Private Attributes
int nx
int ny
int fftw_type
fftwf_complex * array
fftwf_plan f_forward
fftwf_plan f_backward
Detailed Description
Author: Nadia Davidson
Date: Last Modified on 21/2/2011
This class represents a 2D complex field. Setter and getter methods are provided along with some other useful functions (add, multiplying and fast fourier transforming). Complex_2D objects are used in the CDI reconstruction to represent the ESW in a single plane.
Definition at line 54 of file Complex_2D.h.
Constructor & Destructor Documentation
Complex_2D (int x_size, int y_size)
Constructor that creates a 2D object with the given dimensions.
Parameters:
x_size The number of samplings in the horizontal direction
y_size The number of samplings in the vertical direction
Definition at line 14 of file Complex_2D.c++.
References array, f_backward, f_forward, fftw_type, nx, and ny.
~Complex_2D ()
Destructor
Definition at line 62 of file Complex_2D.c++.
References array, f_backward, and f_forward.
Complex_2D (const Complex_2D & object)
Copy Constructor
Definition at line 34 of file Complex_2D.c++.
References array, f_backward, f_forward, fftw_type, get_imag(), get_real(), get_size_x(), get_size_y(), nx, ny, set_imag(), and set_real().
Member Function Documentation
Complex_2D& operator= (const Complex_2D & rhs) [inline]
Assignment Operator
Definition at line 115 of file Complex_2D.h.
References array, f_backward, f_forward, fftw_type, get_imag(), get_real(), get_size_x(), get_size_y(), nx, ny, set_imag(), and set_real().
void set_value (int x, int y, int type, double value)
Set the value at point x,y. Note that this is the slow method. For fast, but unsafe, methods use set_real or set_imag.
Parameters:
x The x position
y The y position
type Which component to set. The options are either: `REAL` or `IMAG`
value The value which it will be set to
Definition at line 90 of file Complex_2D.c++.
References check_bounds(), FAILURE, IMAG, MAG, PHASE, REAL, set_imag(), set_mag(), set_phase(), and set_real().
void set_real (int x, int y, double value) [inline]
Set the real components at point x,y. Note that this is an unsafe method as no bounds checking is performed.
Parameters:
x The x position
y The y position
value The value which it will be set to
Definition at line 191 of file Complex_2D.h.
References array, ny, and REAL.
void set_imag (int x, int y, double value) [inline]
Set the imaginary components at point x,y. Note that this is an unsafe method as no bounds checking is performed.
Parameters:
x The x position
y The y position
value The value which it will be set to
Definition at line 204 of file Complex_2D.h.
References array, IMAG, and ny.
void set_mag (int x, int y, double value) [inline]
Set the magnitude at point x,y, while preserving the phase. Note that this is an unsafe method as no bounds checking is performed.
Parameters:
x The x position
y The y position
value The value which it will be set to
Definition at line 217 of file Complex_2D.h.
References array, get_mag(), IMAG, ny, REAL, set_imag(), and set_real().
void set_phase (int x, int y, double value) [inline]
Set the phase at point x,y, while preserving the magnitude. Note that this is an unsafe method as no bounds checking is performed.
Parameters:
x The x position
y The y position
value The value which it will be set to
Definition at line 238 of file Complex_2D.h.
References get_mag(), set_imag(), and set_real().
double get_real (int x, int y) const [inline]
Get the real components at point x,y. Note that this is an unsafe method as no bounds checking is performed.
Parameters:
x The horizontal position
y The vertical position
Returns: The value at (x,y)
Definition at line 253 of file Complex_2D.h.
References array, ny, and REAL.
double get_imag (int x, int y) const [inline]
Get the imaginary components at point x,y. Note that this is an unsafe method as no bounds checking is performed.
Parameters:
x The horizontal position
y The vertical position
Returns: The value at (x,y)
Definition at line 265 of file Complex_2D.h.
References array, IMAG, and ny.
double get_mag (int x, int y) const [inline]
Get the magnitude at point x,y, $ \sqrt{\mathrm{real}^2 + \mathrm{imag}^2} $ Note that this is an unsafe method as no bounds checking is performed.
Parameters:
x The horizontal position
y The vertical position
Returns: The value at (x,y)
Definition at line 277 of file Complex_2D.h.
References array, IMAG, ny, and REAL.
double get_phase (int x, int y) const [inline]
Get the phase at point x,y. It goes between -pi and pi. Please note that this method is ineffectual when the magnitude is 0. Hence, if you are setting values in a Complex_2D array for the first time, you must use set_mag and then set_phase. Also not, this is an unsafe method as no bounds checking is performed.
Parameters:
x The horizontal position
y The vertical position
Returns: The value at (x,y)
Definition at line 293 of file Complex_2D.h.
References get_imag(), and get_real().
double get_value (int x, int y, int type) const
Get the value at point x,y. Note that this is the slow method. For fast, but unsafe, methods use get_real, get_imag or get_mag.
Parameters:
x The x position
y The y position
type Which component to set. The options are either: `REAL`,`IMAG`,`MAG`,`MAG_SQ` or `PHASE`
Returns: The value
Definition at line 119 of file Complex_2D.c++.
References check_bounds(), FAILURE, get_imag(), get_mag(), get_phase(), get_real(), IMAG, MAG, MAG_SQ, PHASE, and REAL.
int get_size_x () const [inline]
Get the size in x;
Returns: The number of horizontal points.
Definition at line 325 of file Complex_2D.h.
References nx.
int get_size_y () const [inline]
Get the size in y;
Returns: The number of vertical points.
Definition at line 335 of file Complex_2D.h.
References ny.
void get_2d (int type, Double_2D & result) const
Get a 2D array of real numbers.
Parameters:
type Which type of value is wanted. The options are either: `REAL`,`IMAG`,`MAG`,`MAG_SQ` or `PHASE`
result A 2D array. The array will be filled with the result. Note: This method does not allocated memory for the array, so this should be done before making the call.
Definition at line 144 of file Complex_2D.c++.
References get_value(), nx, and ny.
void scale (double scale_factor)
Scale the real and imaginary components of the array by a factor.
Parameters:
scale_factor Number which is multiplied by all components of the field.
Definition at line 154 of file Complex_2D.c++.
References array, IMAG, nx, ny, and REAL.
void add (Complex_2D & c2, double scale = 1)
Add another Complex_2D to this Complex_2D. The values in this object will be modified.
Parameters:
c2 The Complex_2D to add.
scale If this value is non-empty, or not 1, c2 will be scaled before being added to the Complex_2D, ${this} = {this} + {scale} {c2} $ . Using this function is more efficient than calling Complex_2D::scale() followed by Complex_2D:add() separately.
Definition at line 167 of file Complex_2D.c++.
References array, get_imag(), get_real(), get_size_x(), get_size_y(), IMAG, nx, ny, and REAL.
void multiply (Complex_2D & c2, double scale = 1)
Multiple another Complex_2D to this Complex_2D. The values in this object will be modified.
Parameters:
c2 The Complex_2D to add.
scale If this value is non-empty, or not 1, c2 will be scaled before being added to the Complex_2D, ${this} = {this} {scale} {c2} $ . Using this function is more efficient than calling Complex_2D::scale() followed by Complex_2D:multiply() separately.
Definition at line 185 of file Complex_2D.c++.
References get_imag(), get_real(), get_size_x(), get_size_y(), nx, ny, set_imag(), and set_real().
double get_norm () const
Get the norm of this Complex_2D: $ $ .
Returns: $ { {x,y}{ {|C(x,y)|^2} } } $ .
Definition at line 212 of file Complex_2D.c++.
References get_imag(), get_real(), nx, and ny.
Complex_2D * clone () const
Create a new Complex_2D with the same values as this one.
Returns: The new Complex_2D
Definition at line 235 of file Complex_2D.c++.
References Complex_2D(), get_imag(), get_real(), nx, ny, set_imag(), and set_real().
void copy (const Complex_2D & c)
Copy the values from another Complex_2D to this one.
Parameters:
c The Complex_2D which will be copied from.
Definition at line 250 of file Complex_2D.c++.
References array, get_size_x(), get_size_y(), nx, and ny.
void invert (bool scale = false)
Rearrange the matrix so that the corners are placed in the center. This is used after fourier transforming. i.e. if the array is represented by as 4 quadrants:
 1 2
 3 4
It becomes:
 4 3
 2 1
This function may also scale the array while it inverts it, required. This is aimed at reducing the CPU time needed, as both tasks are often performed after fourier transforming.
Parameters:
scale Turn the scaling on-true or off-false. If on, the matrix will be scaled to 1/sqrt(nx*ny) while it is being inverted. By default the array is not scaled.
Definition at line 271 of file Complex_2D.c++.
References get_imag(), get_real(), nx, ny, set_imag(), and set_real().
void perform_forward_fft ()
Forward fourier transform the Complex_2D object. The Complex_2D is not scaled to give the same normalisation as before the transform. The invert() function can be used to acheive this.
Definition at line 419 of file Complex_2D.c++.
References f_forward, and initialise_fft().
void perform_backward_fft ()
Backward fourier transform the Complex_2D object. The Complex_2D is not scaled to give the same normalisation as before the transform. The invert() function can be used to acheive this.
Definition at line 433 of file Complex_2D.c++.
References f_backward, and initialise_fft().
void set_fftw_type (int type) [inline]
A flag which is passed to fftw when plans are created. It maybe either FFTW_ESTIMATE, FFTW_MEASURE or FFTW_PATIENT. See the fftw documentation for a description of each. By default we use FFTW_MEASURE. FFTW_ESTIMATE is used for testing purposes.
Parameters:
type - FFTW_ESTIMATE, FFTW_MEASURE or FFTW_PATIENT
Definition at line 467 of file Complex_2D.h.
References fftw_type.
Complex_2D get_padded (int x_add, int y_add)
Create the same complex with some padding. The padding is filled with 0s
Definition at line 317 of file Complex_2D.c++.
References get_imag(), get_real(), nx, ny, set_imag(), and set_real().
Complex_2D get_unpadded (int x_add, int y_add)
Create the same complex without the some padding.
Definition at line 360 of file Complex_2D.c++.
References get_imag(), get_real(), nx, ny, set_imag(), and set_real().
int check_bounds (int x, int y) const [private]
Check that an (x,y) position is within the bounds of the array
Parameters:
x The horizontal position to check
y The vertical position to check
Definition at line 309 of file Complex_2D.c++.
References FAILURE, nx, ny, and SUCCESS.
void initialise_fft () [private]
Create the fftw plans for forward and backward fast fourier transforms
Definition at line 378 of file Complex_2D.c++.
References array, f_backward, f_forward, fftw_type, nx, and ny.
Field Documentation
int nx [private]
nx/ny are number of samplings in x/y
Definition at line 57 of file Complex_2D.h.
fftwf_complex* array [private]
`array` holds the data
Definition at line 66 of file Complex_2D.h.
The documentation for this class was generated from the following files:
Complex_2D.h
Complex_2D.c++