Real_2D Class Template Reference
Public Member Functions
Real_2D ()
Real_2D (int x_size, int y_size)
~Real_2D ()
void allocate_memory (int x_size, int y_size)
void copy (const Real_2D< T > &other_array)
void set (int x, int y, T value)
T get (int x, int y) const
int get_size_x () const
int get_size_y () const
T get_sum () const
T get_abs_sum () const
T get_max () const
T get_min () const
void add (const Real_2D< T > &other_array, double norm=1.0)
void scale (double scale_by)
void square ()
void sq_root ()
Real_2D (const Real_2D &object)
Real_2D & operator= (const Real_2D &rhs)
Protected Attributes
T * array
int nx
int ny
Detailed Description
template<class T> class Real_2D< T >
Definition at line 33 of file Double_2D.h.
Constructor & Destructor Documentation
Real_2D () [inline]
A constructor which creates an empty array (of no size). Note that memory has not been allocated if this method is used.
Definition at line 54 of file Double_2D.h.
Real_2D (int x_size, int y_size) [inline]
Constructor that creates a 2D object with the given dimensions.
Parameters:
x_size The number of samplings in the horizontal direction
y_size The number of samplings in the vertical direction
Definition at line 62 of file Double_2D.h.
References allocate_memory().
~Real_2D () [inline]
Destructor. Memory is deallocated here.
Definition at line 69 of file Double_2D.h.
References array, and nx.
Real_2D (const Real_2D< T > & object) [inline]
Set the copy constructor
Definition at line 260 of file Double_2D.h.
References allocate_memory(), get(), get_size_x(), get_size_y(), and set().
Member Function Documentation
void allocate_memory (int x_size, int y_size) [inline]
Allocate memory for the array. This should only be used if the constructor was called with no parameters!
Parameters:
x_size The number of samplings in the horizontal direction
y_size The number of samplings in the vertical direction
if(!array){ std::cout << `Could not allocated memory. Exiting..`<<std::endl; exit(); }
Definition at line 83 of file Double_2D.h.
References array, nx, and ny.
void copy (const Real_2D< T > & other_array) [inline]
Copy the contents of another Real_2D array to this one. Note that this is a quick copy method and no bounds checking is done.
Parameters:
other_array The array to copy from
Definition at line 104 of file Double_2D.h.
References array, nx, and ny.
void set (int x, int y, T value) [inline]
Set the value at positions (x,y) WARNING: no bound checking is done!
Parameters:
x The horizontal position
y The vertical position
value The value to set
Definition at line 116 of file Double_2D.h.
References array, and ny.
T get (int x, int y) const [inline]
Get the value at positions (x,y) WARNING: no bound checking is done!
Parameters:
x The horizontal position
y The vertical position
Returns: The value at (x,y)
Definition at line 129 of file Double_2D.h.
References array, and ny.
int get_size_x () const [inline]
Get the size in x;
Returns: The number of horizontal points.
Definition at line 139 of file Double_2D.h.
References nx.
int get_size_y () const [inline]
Get the size in y;
Returns: The number of vertical points.
Definition at line 149 of file Double_2D.h.
References ny.
T get_sum () const [inline]
Get the sum of all values in the array. This is useful to determine normalisation values.
Returns: The sum of all values in the array
Definition at line 161 of file Double_2D.h.
References array, nx, and ny.
T get_abs_sum () const [inline]
Get the sum of the abolute value of all elements in the array.
Returns: The sum of the abosulute values of all elements in the array
Definition at line 175 of file Double_2D.h.
References array, nx, and ny.
T get_max () const [inline]
Get the maximum of all values in the array.
Returns: The maximum value in the array
Definition at line 190 of file Double_2D.h.
References array, nx, and ny.
T get_min () const [inline]
Get the minimum of all values in the array.
Returns: The minimum value in the array
Definition at line 210 of file Double_2D.h.
References array, nx, and ny.
void square () [inline]
Square all array values in-place.
Definition at line 241 of file Double_2D.h.
References array, nx, and ny.
void sq_root () [inline]
Square-root all array values in-place.
Definition at line 250 of file Double_2D.h.
References array, nx, and ny.
Real_2D& operator= (const Real_2D< T > & rhs) [inline]
Set the assignment operator
Definition at line 272 of file Double_2D.h.
References allocate_memory(), array, get(), get_size_x(), get_size_y(), nx, and set().
Field Documentation
T* array [protected]
the underlying 2-D array
Definition at line 38 of file Double_2D.h.
int nx [protected]
the size in x
Definition at line 41 of file Double_2D.h.
int ny [protected]
the size in y
Definition at line 44 of file Double_2D.h.
The documentation for this class was generated from the following file:
Double_2D.h