PartialCDI Class Reference
The class which performs partially coherent reconstruction.
#include <PartialCDI.h>
Public Types
CROSS_CORRELATION
MINIMUM_ERROR
enum { CROSS_CORRELATION,
MINIMUM_ERROR
 }
Public Member Functions
PartialCDI (Complex_2D &initial_guess, double lcx=1.0, double lcy=1.0, double pxsize=1.0, double pysize=1.0, double energy=1.0, double zsd=1.0, int nleg=2, int nmode=2, unsigned int n_best=0)
~PartialCDI ()
void initialise_estimate ()
void initialise_estimate (int seed)
int iterate ()
void initialise_matrices (int leg, int modes)
Complex_2D get_transmission ()
void set_transmission (Complex_2D &new_transmission)
Double_2D propagate_modes_to_detector ()
Complex_2D get_mode (int mode)
void set_threshold (double d)
Complex_2D * get_best_result (double &error, int index=0)
void set_support (const Double_2D &object_support, bool soften=false)
void set_intensity (const Double_2D &detector_intensity)
void set_beam_stop (const Double_2D &beam_stop_region)
void set_relaxation_parameter (double relaxation_parameter)
int get_size_x ()
int get_size_y ()
const Complex_2D & get_exit_surface_wave ()
void set_exit_surface_wave (Complex_2D &esw)
void set_algorithm (int alg)
void set_custom_algorithm (double m1, double m2, double m3, double m4, double m5, double m6, double m7, double m8, double m9, double m10)
void print_algorithm ()
double get_error ()
virtual void apply_shrinkwrap (double gauss_width=1.5, double threshold=0.1)
const Double_2D & get_support ()
virtual void apply_support (Complex_2D &c)
virtual void project_intensity (Complex_2D &c)
virtual void scale_intensity (Complex_2D &c)
void set_fftw_type (int type)
virtual void set_complex_constraint (TransmissionConstraint &trans_constraint)
void reset_best ()
Static Public Member Functions
static int getAlgFromName (std::string algorithm_name)
Protected Member Functions
void apply_threshold (Double_2D &array, double threshold)
void convolve (Double_2D &array, double gauss_width, int pixel_cut_off=4)
void support_constraint (Complex_2D &c)
void reallocate_temp_complex_memory ()
void update_n_best ()
Static Protected Member Functions
static std::map< std::string, int > * set_up_algorithm_name_map ()
Protected Attributes
std::vector< Complex_2D > singleCDI
std::vector< Complex_2D > singlemode
std::vector< Double_2D * > weights
std::vector< double > x_position
std::vector< double > y_position
Complex_2D transmission
std::vector< double > eigen
int iterations_per_cycle
int nleg
int nmode
double lcy
double lcx
double pxsize
double pysize
double zsd
double energy
double threshold
Complex_2D * jmatrix
Complex_2D * hmatrix
Complex_2D * smatrix
Complex_2D & complex
int nx
int ny
Complex_2D * temp_complex_PFS
Complex_2D * temp_complex_PF
Complex_2D * temp_complex_PS
Complex_2D * temp_complex_PSF
double beta
Double_2D support
Double_2D intensity_sqrt
Double_2D * beam_stop
int algorithm
double algorithm_structure [NTERMS]
double current_error
int n_best
Complex_2D ** best_array
double * best_error_array
TransmissionConstraint * transmission_constraint
Static Protected Attributes
static std::map< std::string, int > * algNameMap = BaseCDI::set_up_algorithm_name_map()
Private Member Functions
void reallocate_transmission_memory (int new_nx, int new_ny)
void scale_object (double factor)
void propagate_from_detector (Complex_2D &c)
void propagate_to_detector (Complex_2D &c)
void apply_transmission (Complex_2D &c)
void scale_intensity (std::vector< Complex_2D > &c)
Double_2D sum_intensity (std::vector< Complex_2D > &c)
void update_transmission ()
void fill_jmatrix (Double_2D legmatrix, Double_2D roots)
void fill_smatrix (Double_2D legmatrix, Double_2D roots)
void fill_modes (Complex_2D &c)
Detailed Description
Author: T'Mir Julius <cxs-softwarse@physics.unimelb.edu.au>
This class can be used to perform partially coherent reconstruction of plane-wave partialy CDI data. The number of modes and legendre polynomials used is defined by the user. The number of Legendre polynomial * must exceed the number of modes.
Definition at line 28 of file PartialCDI.h.
Constructor & Destructor Documentation
~PartialCDI ()
Destructor for PhaseDiverseCDI
Definition at line 84 of file PartialCDI.c++.
Member Function Documentation
void initialise_estimate ()
Initialise the estimate of the 'global' object function. The initialisation is performed using the current estimate for each 'local' frame. For this reason you must first initialise each FresnelCDI/PlanarCDI object individually before calling this function.
void initialise_estimate (int seed) [virtual]
Set the values in the Complex_2D to an initial estimate. For BaseCDI, this is set to random numbers inside the support for both the real and complex components, and zero outside the support.
Parameters:
seed The seed for the random number generator. By default this is 0.
Implements BaseCDI p..
Definition at line 118 of file PartialCDI.c++.
References BaseCDI::complex, IMAG, BaseCDI::intensity_sqrt, nleg, nmode, BaseCDI::nx, BaseCDI::ny, REAL, Complex_2D::set_value(), BaseCDI::support, and transmission.
int iterate () [virtual]
The iterate the algorithm. This overwrites the the class of the same name in BaseCDI.
Reimplemented from BaseCDI p..
Definition at line 156 of file PartialCDI.c++.
References BaseCDI::algorithm, BaseCDI::algorithm_structure, BaseCDI::apply_support(), apply_transmission(), BaseCDI::nx, BaseCDI::ny, propagate_from_detector(), propagate_to_detector(), scale_intensity(), singleCDI, singlemode, SUCCESS, BaseCDI::temp_complex_PF, BaseCDI::temp_complex_PFS, BaseCDI::temp_complex_PS, BaseCDI::temp_complex_PSF, BaseCDI::update_n_best(), and update_transmission().
void initialise_matrices (int leg, int modes)
generate the S and J matrices for the decomposition of the partially coherent wave where JC=nSC where H = integral(P*l(r1)J(r1, r2)Pm(r2)) dr1 dr2 and S=integral(P*l(r)pm(r))dr where Pl is an orhtonormal basis set, in this case, the Legendre polynomials
Definition at line 408 of file PartialCDI.c++.
References BaseCDI::complex, eigen, fill_jmatrix(), fill_modes(), fill_smatrix(), jmatrix, nleg, nmode, BaseCDI::nx, BaseCDI::ny, Complex_2D::set_imag(), Complex_2D::set_real(), singlemode, and smatrix.
Complex_2D get_transmission ()
This function allows you to access the 'global' sample function.
Returns: The current estimate of either the transmission (for FresnelCDI) or exit-surface-wave (for PlanarCDI)
Definition at line 89 of file PartialCDI.c++.
References transmission.
void set_transmission (Complex_2D & new_transmission)
Set the 'global' sample function. This method could be used, for example, instead of 'initialise_estimate' to initialise the results to those from a previous reconstruction.
Parameters:
new_transmission The transmission function exit-surface-wave to copy.
Definition at line 95 of file PartialCDI.c++.
References BaseCDI::complex, Complex_2D::copy(), Complex_2D::get_size_x(), Complex_2D::get_size_y(), BaseCDI::nx, BaseCDI::ny, and transmission.
Double_2D propagate_modes_to_detector ()
Propagates the modes to the detector. Specifically for use with the simulations
Definition at line 647 of file PartialCDI.c++.
References apply_transmission(), eigen, BaseCDI::nx, BaseCDI::ny, propagate_to_detector(), singleCDI, and singlemode.
Complex_2D get_mode (int mode)
Returns a given mode. If the mode requested is too big, it returns the final mode
Definition at line 674 of file PartialCDI.c++.
References eigen, Complex_2D::multiply(), BaseCDI::nx, BaseCDI::ny, and singlemode.
void set_threshold (double d) [inline]
Set the minimum contribution of a mode as a proportion of the dominant mode for it to be included in the reconstruction
Definition at line 190 of file PartialCDI.h.
References threshold.
void reallocate_transmission_memory (int new_nx, int new_ny) [private]
This function is used to reallocate memory for the 'global' sample object. It is only used when add_new_position is called, in the case that the frame does not fit within the bounds of the current object array.
void scale_object (double factor) [private]
This function is used during reconstruction in parallel mode. It is similar to simply scaling all the elements of the 'global' sample array, (e.g. with object.scale(factor). However, this method preserves the value of the elements outside the boundary of the sample. ie. it checks the weights of all the local frames to work out which area to scale.
Parameters:
factor The scaled elements go from 'a' to 'factor*a'.
void propagate_from_detector (Complex_2D & c) [private, virtual]
Propagate the CDI's
Implements BaseCDI p..
Definition at line 638 of file PartialCDI.c++.
References Complex_2D::invert(), and Complex_2D::perform_backward_fft().
void propagate_to_detector (Complex_2D & c) [private, virtual]
Propagate to the sample plane using a fast fourier transform.
Parameters:
c The Complex_2D field to propagate
Implements BaseCDI p..
Definition at line 630 of file PartialCDI.c++.
References Complex_2D::invert(), and Complex_2D::perform_forward_fft().
void apply_transmission (Complex_2D & c) [private]
uses the complex_2d multiply function to apply the transmission function
Definition at line 280 of file PartialCDI.c++.
References BaseCDI::complex, and Complex_2D::multiply().
void scale_intensity (std::vector< Complex_2D > & c) [private]
scale the highest occupancy mode this overwrites the function of the same name in BaseCDI
Parameters:
c The Complex_2d to be scaled
Definition at line 287 of file PartialCDI.c++.
References BaseCDI::beam_stop, BaseCDI::current_error, BaseCDI::intensity_sqrt, BaseCDI::nx, BaseCDI::ny, and sum_intensity().
Double_2D sum_intensity (std::vector< Complex_2D > & c) [private]
add the intensities across all modes
Definition at line 339 of file PartialCDI.c++.
References eigen, BaseCDI::nx, and BaseCDI::ny.
void update_transmission () [private]
calculate the transmission function by dividing the highest occupacy mode at the source by the highest occupancy mode at the detector
Definition at line 371 of file PartialCDI.c++.
References BaseCDI::algorithm, BaseCDI::apply_support(), BaseCDI::complex, BaseCDI::nx, BaseCDI::ny, Complex_2D::set_imag(), Complex_2D::set_real(), singleCDI, singlemode, and transmission.
void fill_jmatrix (Double_2D legmatrix, Double_2D roots) [private]
the J matrix where J = integral(P*l(r1)J(r1, r2)Pm(r2))dr1dr2 the x and y are computed seperately, then multiplied together. The result is a matrix of xn+y by in+j where
Definition at line 513 of file PartialCDI.c++.
References Complex_2D::get_imag(), Complex_2D::get_real(), jmatrix, lcx, lcy, nleg, nmode, Complex_2D::set_imag(), and Complex_2D::set_real().
void fill_smatrix (Double_2D legmatrix, Double_2D roots) [private]
the S matrix = integral(P*l(r)pm(r))dr = 2/(2n+1) from the orthogonality requirments of Legendre Polynomials. We then turn it in to a 2D matrix for the x and y dimensions
Definition at line 471 of file PartialCDI.c++.
References Complex_2D::get_real(), nleg, nmode, Complex_2D::set_imag(), Complex_2D::set_real(), and smatrix.
void fill_modes (Complex_2D & c) [private]
fill a vector of Complex_2D for single modes. These modes do not evolve over time, and so are not BaseCDI's
Definition at line 585 of file PartialCDI.c++.
References eigen, Complex_2D::get_imag(), Complex_2D::get_real(), nmode, BaseCDI::nx, BaseCDI::ny, singlemode, threshold, x_position, and y_position.
Complex_2D * get_best_result (double & error, int index = 0) [inherited]
While the reconstruction is running this object will store the `n_best` number of best estimates according to the error metric. So, for example, if HIO is used and the error enters and leaves an error minima during reconstruction, the best (ie. lowest error) Complex_2D results will be kept. They can then be retrieved using this method.
Parameters:
index get best result number `index`. 0 is the best, 1 is the 2nd best etc...
error `error` is filled with the metric error of the selected best result
Definition at line 82 of file BaseCDI.c++.
References BaseCDI::best_array, BaseCDI::best_error_array, and BaseCDI::n_best.
void set_support (const Double_2D & object_support, bool soften = false) [inherited]
Set the sample support. A `0` value in the Double_2D is interpreted as being outside the support. Pixels with the maximum value of the Double_2D are considered inside the support. Values between 0 and the maximum indict the soft edge of the support. In this case, when the support is applied, the esw magnitude is scaled relative to the support edge value.
By default, the edge of a given support will be softened by convolution with a 3 pixel wide gaussian. This feature can be turned off by setting the boolean flag to false.
The support can be updated at anytime during reconstruction by calling this method.
Parameters:
object_support The sample support
soften If true, the edges of the support will be softened by covolving it with a 3 pixel wide gaussian. By default this option is off.
Definition at line 95 of file BaseCDI.c++.
References BaseCDI::convolve(), BaseCDI::nx, BaseCDI::ny, and BaseCDI::support.
void set_intensity (const Double_2D & detector_intensity) [inherited]
Set the detector diffraction image (i.e. the square of the amplitude of the wavefield at the detector).
Parameters:
detector_intensity The intensity at the detector
Reimplemented in PartialCharCDI p..
Definition at line 115 of file BaseCDI.c++.
References BaseCDI::intensity_sqrt, BaseCDI::nx, and BaseCDI::ny.
void set_beam_stop (const Double_2D & beam_stop_region) [inherited]
Set the beam-stop position in the detector plane. This region will be leaf to float when the intensity if scaled during reconstruction. A zero in the array provided represents the beam stop and all other values represent the region which should be scaled.
Parameters:
beam_stop_region The region of the beam stop in the detector plane
Definition at line 109 of file BaseCDI.c++.
References BaseCDI::beam_stop, BaseCDI::nx, and BaseCDI::ny.
void set_relaxation_parameter (double relaxation_parameter) [inline, inherited]
Set the relaxation parameters of the reconstruction algorithm. This is $ \beta $ used exactly as it is in Harry's review paper. This maybe reset at anytime during the reconstruction by calling this method. The default value is 0.9.
Parameters:
relaxation_parameter The algorithm relaxation_parameter
Reimplemented in FresnelCDI_WF p..
Definition at line 261 of file BaseCDI.h.
References BaseCDI::algorithm, BaseCDI::beta, and BaseCDI::set_algorithm().
int get_size_x () [inline, inherited]
Returns: the number of pixel along the x-axis.
Definition at line 270 of file BaseCDI.h.
References BaseCDI::nx.
int get_size_y () [inline, inherited]
Returns: the number of pixel along the y-axis.
Definition at line 278 of file BaseCDI.h.
References BaseCDI::ny.
void set_algorithm (int alg) [inherited]
Set the algorithm. By default HIO is used.
Parameters:
alg The algorithm. The options are:
 ER - error reduction
 BIO - basic input-output
 BOO - basic output-output
 HIO - hybrid input-output
 DM - difference map
 SF - solvent-flipping
 ASR - averaged successive reflections
 HPR - hybrid projection reflection
 RAAR - relaxed averaged alternating reflectors
Reimplemented in FresnelCDI_WF p..
Definition at line 189 of file BaseCDI.c++.
References BaseCDI::algorithm, BaseCDI::beta, and BaseCDI::set_custom_algorithm().
void set_custom_algorithm (double m1, double m2, double m3, double m4, double m5, double m6, double m7, double m8, double m9, double m10) [inherited]
Iterative reconstruction algorithms can be expressed as a combination of the following 5 operators:
$ \hat{P}_S \hat{P}_F$, $\hat{P}_F \hat{P}_S$ , $ \hat{P}_S $ , $ \hat{P}_F $ and $ \hat{I} $
 Where $ \hat{P}_S $ is the support projection and $ \hat{P}_F $ is the intensity projection. These can be combined to form a basis of 10 vectors (see Harray's review). The parameters to this method set the coefficient for each of these vectors. Note: the vector set is linearly dependant.
Please see page 22 of the H.M. Quiney review: TUTORIAL REVIEW, Coherent diffractive imaging using short wavelength light sources, Journal of Modern Optics, 2010, DOI: 10.1080/09500340.2010.495459
Parameters:
m1 Coefficient to the $ [ \hat{P}_S \hat{P}_F - \hat{P}_F \hat{P}_S ]x_k $ term
m2 Coefficient to the $ [ \hat{P}_S \hat{P}_F - \hat{P}_F ]x_k $ term
m3 Coefficient to the $ [ \hat{P}_S \hat{P}_F - \hat{P}_S ]x_k $ term
m4 Coefficient to the $ [ \hat{P}_S \hat{P}_F - \hat{I} ]x_k $ term
m5 Coefficient to the $ [ \hat{P}_F \hat{P}_S - \hat{P}_F ]x_k $ term
m6 Coefficient to the $ [ \hat{P}_F \hat{P}_S - \hat{P}_S ]x_k $ term
m7 Coefficient to the $ [ \hat{P}_F \hat{P}_S - \hat{I} ]x_k $ term
m8 Coefficient to the $ [ \hat{P}_F - \hat{P}_S ]x_k $ term
m9 Coefficient to the $ [ \hat{P}_F - \hat{I} ]x_k $ term
m10 Coefficient to the $ [ \hat{P}_S - \hat{I} ]x_k $ term
Reimplemented in FresnelCDI_WF p..
Definition at line 237 of file BaseCDI.c++.
References BaseCDI::algorithm, BaseCDI::algorithm_structure, and BaseCDI::reallocate_temp_complex_memory().
void print_algorithm () [inherited]
Print the current algorithm to standard output. The algorithm is in the form:
 $ x_{k+1} = x_k + (a \hat{P}_S \hat{P}_F + b \hat{P}_F \hat{P}_S + c \hat{P}_S + d \hat{P}_F + e \hat{I} )x_k $
Reimplemented in FresnelCDI_WF p..
Definition at line 275 of file BaseCDI.c++.
References BaseCDI::algorithm, and BaseCDI::algorithm_structure.
double get_error () [inherited]
Get the difference between the estimated diffraction and the actual diffraction pattern.
 $ \chi^2 = \frac { \sum_{pixels} ( M_{pixel} - \sqrt{I_{pixel}} )^2 } { \sum_{pixels} {I_{pixel}} } $.
 Where $ M $ is the magnitude of the current estimate and $ I $ is the measured intensity.
NOTE: This method actually gives you the error for the previous iteration. This is because it's much faster to calculate the error during the intensity scaling step of the iteration rather than performing a FFT just for the error calculation.
Returns: The error metric
Definition at line 123 of file BaseCDI.c++.
References BaseCDI::current_error.
static int getAlgFromName (std::string algorithm_name) [inline, static, inherited]
Given the name of an algorithm, e.g. `HIO`, return the unique integer identifier. This is used by the configuration file reader, and probably won't be needed by users.
Parameters:
algorithm_name The algorithm name
Returns: The integer identifier
Definition at line 379 of file BaseCDI.h.
References BaseCDI::algNameMap.
void apply_shrinkwrap (double gauss_width = 1.5, double threshold = 0.1) [virtual, inherited]
Apply the shrinkwrap algorithm. The magnitude of the current ESW estimate will be convolved with a Gaussian, thresholded and set as the new support.
Parameters:
gauss_width The width ($ \sigma $) of the Gaussian in pixels. The default is 1.5.
threshold The threshold which is applied, as a fraction of the maximum pixel value. The default is 0.1 (10%).
Definition at line 413 of file BaseCDI.c++.
References BaseCDI::apply_threshold(), BaseCDI::complex, BaseCDI::convolve(), Complex_2D::get_2d(), MAG, BaseCDI::nx, BaseCDI::ny, and BaseCDI::set_support().
const Double_2D& get_support () [inline, inherited]
Get the current support. This might be useful if shrinkwrap has been applied, as it allows you to get the updated support.
Returns: An object reference to the current support.
Definition at line 405 of file BaseCDI.h.
References BaseCDI::support.
void apply_support (Complex_2D & c) [virtual, inherited]
Apply the support constraint.
Parameters:
c The complex field to apply the support constraint on
Reimplemented in FresnelCDI p..
Definition at line 127 of file BaseCDI.c++.
References TransmissionConstraint::apply_constraint(), BaseCDI::support_constraint(), and BaseCDI::transmission_constraint.
void project_intensity (Complex_2D & c) [virtual, inherited]
Apply the intensity constraint. The ESW is projected to the detector plane, the intensity is scaled to match the measured data and the field is projected back into the sample plane.
Parameters:
c The complex field to apply the intensity constraint on
Definition at line 153 of file BaseCDI.c++.
References BaseCDI::propagate_from_detector(), BaseCDI::propagate_to_detector(), and BaseCDI::scale_intensity().
void scale_intensity (Complex_2D & c) [virtual, inherited]
The intensity is scaled to match the measured data. The error is updated in this method.
Parameters:
c The complex field to apply the scaling to
Reimplemented in FresnelCDI p., PartialCharCDI p., and PolyCDI p..
Definition at line 160 of file BaseCDI.c++.
References BaseCDI::beam_stop, BaseCDI::current_error, Complex_2D::get_mag(), BaseCDI::intensity_sqrt, BaseCDI::nx, BaseCDI::ny, and Complex_2D::set_mag().
void set_fftw_type (int type) [inherited]
A flag which is used for the fast fourier transforms to select the fft algorithm. It maybe either FFTW_ESTIMATE, FFTW_MEASURE or FFTW_PATIENT. See the fftw documentation for a description of each. By default we use FFTW_MEASURE. FFTW_ESTIMATE is used for testing purposes.
Parameters:
type - FFTW_ESTIMATE, FFTW_MEASURE or FFTW_PATIENT
Definition at line 491 of file BaseCDI.c++.
References BaseCDI::complex, Complex_2D::set_fftw_type(), BaseCDI::temp_complex_PF, and BaseCDI::temp_complex_PFS.
virtual void set_complex_constraint (TransmissionConstraint & trans_constraint) [inline, virtual, inherited]
void set_complex_constraint_function(void (*complex_constraint)(Complex_2D & tranmission)){ custom_complex_constraint = complex_constraint; }
Definition at line 468 of file BaseCDI.h.
References BaseCDI::transmission_constraint.
map< string, int > * set_up_algorithm_name_map () [static, protected, inherited]
Sets up the mapping between algorithm name and number. This is only called during the initialisation and should not be called elsewhere.
Returns: The algorithm name-iteger mapping
Definition at line 14 of file BaseCDI.c++.
void apply_threshold (Double_2D & array, double threshold) [protected, inherited]
Apply a threshold to the values in `array`.
Parameters:
array The array to be thresholded
threshold The threshold which is applied, as a fraction of the maximum pixel value. The default is 0.1 (10%).
Definition at line 474 of file BaseCDI.c++.
References BaseCDI::nx.
void convolve (Double_2D & array, double gauss_width, int pixel_cut_off = 4) [protected, inherited]
Convolved `array` with a 2-D Gaussian function. To speed up computation we only convolve up to 4 pixels away from the Gaussian peak.
Parameters:
array The array to be convolved
gauss_width The width ($ \sigma $) of the Gaussian in pixels. The default is 1.5.
pixel_cut_off Convolve up to 4 pixels away from the Gaussian peak.
Definition at line 429 of file BaseCDI.c++.
References BaseCDI::nx, and BaseCDI::ny.
Field Documentation
std::vector<Complex_2D> singleCDI [protected]
A vector holding a pointer to each of the FresnelCDI/PlanarCDI objects
Definition at line 35 of file PartialCDI.h.
std::vector<Complex_2D> singlemode [protected]
A vector holding the initial wave described as a series of modes.
Definition at line 39 of file PartialCDI.h.
std::vector<Double_2D * > weights [protected]
A vector holding the weighting function for each frame
Definition at line 42 of file PartialCDI.h.
std::vector<double> x_position [protected]
A vector of the transverse positions in x
Definition at line 46 of file PartialCDI.h.
std::vector<double> y_position [protected]
A vector of the transverse positions in y
Definition at line 50 of file PartialCDI.h.
Complex_2D transmission [protected]
The current estimate of the transmission function
Definition at line 53 of file PartialCDI.h.
std::vector<double> eigen [protected]
An array of the eigenvectors for the system of JC=nSC
Definition at line 56 of file PartialCDI.h.
int iterations_per_cycle [protected]
The number of iterations to perform for each 'local' frame
Definition at line 59 of file PartialCDI.h.
int nleg [protected]
The number of orthogonal components for the light source.
Definition at line 62 of file PartialCDI.h.
int nmode [protected]
The number of component modes for the light source. nleg must be bigger than nmode
Definition at line 66 of file PartialCDI.h.
double lcy [protected]
Coherence length x
Definition at line 69 of file PartialCDI.h.
double lcx [protected]
Coherence length y
Definition at line 71 of file PartialCDI.h.
double pxsize [protected]
The size of a pixel x
Definition at line 74 of file PartialCDI.h.
double pysize [protected]
The size of a pixel y
Definition at line 76 of file PartialCDI.h.
double zsd [protected]
The distance between the sample and detector
Definition at line 79 of file PartialCDI.h.
double energy [protected]
The energy of the beam
Definition at line 82 of file PartialCDI.h.
double threshold [protected]
The minimum value of the contribution of a mode as a proportion of the dominant mode
Definition at line 87 of file PartialCDI.h.
Complex_2D* jmatrix [protected]
The J matrix for the decomposition of the partially coherent wave where JC=nSC
Definition at line 92 of file PartialCDI.h.
Complex_2D* hmatrix [protected]
The H matrix where H = integral(P*l(r1)J(r1, r2)Pm(r2)) dr1 dr2
Definition at line 97 of file PartialCDI.h.
Complex_2D* smatrix [protected]
The S matrices for the decomposition of the partially coherent wave where JC=nSC where
Definition at line 102 of file PartialCDI.h.
Complex_2D& complex [protected, inherited]
a reference to the Complex_2D object which is altered during each iteration
Definition at line 91 of file BaseCDI.h.
int nx [protected, inherited]
The samplings in x
Definition at line 94 of file BaseCDI.h.
int ny [protected, inherited]
The samplings in y
Definition at line 97 of file BaseCDI.h.
Complex_2D* temp_complex_PFS [protected, inherited]
temporary Complex_2Ds which are used in the computation of the PFS and PF terms for each iteration.
Definition at line 105 of file BaseCDI.h.
double beta [protected, inherited]
the relaxation parameter
Reimplemented in PolyCDI p..
Definition at line 111 of file BaseCDI.h.
Double_2D support [protected, inherited]
a copy of the support
Definition at line 114 of file BaseCDI.h.
Double_2D intensity_sqrt [protected, inherited]
a copy of the square root of the intensity at the detector plane.
Definition at line 117 of file BaseCDI.h.
Double_2D* beam_stop [protected, inherited]
A mask of the beam-stop which is used when scaling the intensity
Definition at line 120 of file BaseCDI.h.
int algorithm [protected, inherited]
the algorithm which is being used: ER, HIO etc.
Definition at line 123 of file BaseCDI.h.
double algorithm_structure[NTERMS] [protected, inherited]
an array which holds the structure of the algorithm. i.e. the coefficients for each term in the iteration equation.
Definition at line 127 of file BaseCDI.h.
double current_error [protected, inherited]
the difference between the intensity in the detector plane the current estimated intensity.
Definition at line 131 of file BaseCDI.h.
int n_best [protected, inherited]
how many best estimates to store
Definition at line 134 of file BaseCDI.h.
Complex_2D** best_array [protected, inherited]
array of the best estimates
Definition at line 137 of file BaseCDI.h.
double* best_error_array [protected, inherited]
array of the error corresponding to each of the best estimates
Definition at line 141 of file BaseCDI.h.
TransmissionConstraint* transmission_constraint [protected, inherited]
a function pointer to a cumstomized complex constraint
Definition at line 145 of file BaseCDI.h.
map< string, int > * algNameMap = BaseCDI::set_up_algorithm_name_map() [static, protected, inherited]
a mapping between the algorithm name (string) and identification number
Definition at line 149 of file BaseCDI.h.
The documentation for this class was generated from the following files:
PartialCDI.h
PartialCDI.c++