BaseCDI Class Reference
The class which performs planar CDI reconstruction.
#include <BaseCDI.h>
Public Member Functions
BaseCDI (Complex_2D &complex, unsigned int n_best=0)
virtual ~BaseCDI ()
virtual int iterate ()
virtual void initialise_estimate (int seed=0)=0
Complex_2D * get_best_result (double &error, int index=0)
void set_support (const Double_2D &object_support, bool soften=false)
void set_intensity (const Double_2D &detector_intensity)
void set_beam_stop (const Double_2D &beam_stop_region)
void set_relaxation_parameter (double relaxation_parameter)
int get_size_x ()
int get_size_y ()
const Complex_2D & get_exit_surface_wave ()
void set_exit_surface_wave (Complex_2D &esw)
void set_algorithm (int alg)
void set_custom_algorithm (double m1, double m2, double m3, double m4, double m5, double m6, double m7, double m8, double m9, double m10)
void print_algorithm ()
double get_error ()
virtual void apply_shrinkwrap (double gauss_width=1.5, double threshold=0.1)
const Double_2D & get_support ()
virtual void apply_support (Complex_2D &c)
virtual void project_intensity (Complex_2D &c)
virtual void scale_intensity (Complex_2D &c)
virtual void propagate_to_detector (Complex_2D &c)=0
virtual void propagate_from_detector (Complex_2D &c)=0
void set_fftw_type (int type)
virtual void set_complex_constraint (TransmissionConstraint &trans_constraint)
void reset_best ()
Static Public Member Functions
static int getAlgFromName (std::string algorithm_name)
Protected Member Functions
void apply_threshold (Double_2D &array, double threshold)
void convolve (Double_2D &array, double gauss_width, int pixel_cut_off=4)
void support_constraint (Complex_2D &c)
void reallocate_temp_complex_memory ()
void update_n_best ()
Static Protected Member Functions
static std::map< std::string, int > * set_up_algorithm_name_map ()
Protected Attributes
Complex_2D & complex
int nx
int ny
Complex_2D * temp_complex_PFS
Complex_2D * temp_complex_PF
Complex_2D * temp_complex_PS
Complex_2D * temp_complex_PSF
double beta
Double_2D support
Double_2D intensity_sqrt
Double_2D * beam_stop
int algorithm
double algorithm_structure [NTERMS]
double current_error
int n_best
Complex_2D ** best_array
double * best_error_array
TransmissionConstraint * transmission_constraint
Static Protected Attributes
static std::map< std::string, int > * algNameMap = BaseCDI::set_up_algorithm_name_map()
Detailed Description
Author: Nadia Davidson <nadiamd@unimelb.edu.au>
The fundamental class used for performing CDI reconstruction; an object of type `BaseCDI` allows planar CDI to be performed, and it is also used by the Fresnel reconstruction code (through inheritance).
The reconstruction can be performed in the following way:
The user should create an object to store the result (the exit surface wave of type Complex_2D). For example using:
Complex_2D esw_estimate(nx,ny)
This can be initialise to a best guess, or can be left for the BaseCDI object to initialise.
The BaseCDI object should be created and the Complex_2D previously created should be passed as input. For example:
BaseCDI my_planar_recon(esw_estimate)
The support and intensity data should be set, and the exit surface wave initialised to a first guess (if not already done):
my_planar_recon.set_support(support)
my_planar_recon.set_intensity(data)
my_planar_recon.initialise_estimate()
The reconstruction can be configured before, or at anytime during the reconstruction using setter methods. For example the algorithm choice and relaxation parameters:
my_planar_recon.set_algorithm(HIO)
my_planar_recon.set_relaxation_parameter(0.95)
The algorithm is fully customisable through the BaseCDI::set_custom_algorithm method. See page 22 of the H.M. Quiney review: TUTORIAL REVIEW, Coherent diffractive imaging using short wavelength light sources, Journal of Modern Optics, 2010, DOI: 10.1080/09500340.2010.495459 for the formalism.
The reconstruction is then performed with multiple calls to the BaseCDI::iterate() method:
my_planar_recon.iterate()
This will automatically update the values in the Complex_2D estimate and the current error. The error can be retrieved using BaseCDI::get_current_error().
For cases where the beam-stop region must be excluded during reconstruction, you should call the set_beam_stop() method, to define the beam-stop region before running iterate().
Definition at line 85 of file BaseCDI.h.
Constructor & Destructor Documentation
BaseCDI (Complex_2D & complex, unsigned int n_best = 0)
Constructor. The default algorithms is set to HIO with a relaxation parameter of 0.9.
Parameters:
complex The complex 2-D field which is modified by this object. This represents the exit-surface-wave of the sample. It may be pre-initialised to a best first guess (e.g manually); it may be loaded from a file (e.g. the output from a previous reconstruction job); or it may be unitialised, and the default initialisation provided by BaseCDI may be used.
n_best The number of `best estimates` to keep. See BaseCDI::get_best_result below for more detail. By default this option is set to zero.
Definition at line 32 of file BaseCDI.c++.
References algorithm, beam_stop, best_array, best_error_array, nx, ny, set_algorithm(), temp_complex_PF, temp_complex_PFS, temp_complex_PS, temp_complex_PSF, and transmission_constraint.
~BaseCDI () [virtual]
Destructor. This is not interesting for users.
Definition at line 68 of file BaseCDI.c++.
References algorithm_structure, best_array, best_error_array, n_best, NTERMS, and reallocate_temp_complex_memory().
Member Function Documentation
int iterate () [virtual]
The main method for running the reconstruction! This method transforms the Complex_2D given to it according to:
$ x_{k+1} = g ( x_{k} ) $
 Where $g()$ depends on the algorithm used. The current error is also updated when this method is called.
Reimplemented in FresnelCDI_WF p., PartialCDI p., and PolyCDI p..
Definition at line 294 of file BaseCDI.c++.
References algorithm, algorithm_structure, apply_support(), complex, Complex_2D::copy(), Complex_2D::get_imag(), Complex_2D::get_real(), nx, ny, project_intensity(), Complex_2D::set_imag(), Complex_2D::set_real(), SUCCESS, temp_complex_PF, temp_complex_PFS, temp_complex_PS, temp_complex_PSF, and update_n_best().
virtual void initialise_estimate (int seed = 0) [pure virtual]
Set the values in the Complex_2D to an initial estimate. For BaseCDI, this is set to random numbers inside the support for both the real and complex components, and zero outside the support.
Parameters:
seed The seed for the random number generator. By default this is 0.
Implemented in FresnelCDI p., FresnelCDI_WF p., PartialCDI p., PartialCharCDI p., PlanarCDI p., and PolyCDI p..
Complex_2D * get_best_result (double & error, int index = 0)
While the reconstruction is running this object will store the `n_best` number of best estimates according to the error metric. So, for example, if HIO is used and the error enters and leaves an error minima during reconstruction, the best (ie. lowest error) Complex_2D results will be kept. They can then be retrieved using this method.
Parameters:
index get best result number `index`. 0 is the best, 1 is the 2nd best etc...
error `error` is filled with the metric error of the selected best result
Definition at line 82 of file BaseCDI.c++.
References best_array, best_error_array, and n_best.
void set_support (const Double_2D & object_support, bool soften = false)
Set the sample support. A `0` value in the Double_2D is interpreted as being outside the support. Pixels with the maximum value of the Double_2D are considered inside the support. Values between 0 and the maximum indict the soft edge of the support. In this case, when the support is applied, the esw magnitude is scaled relative to the support edge value.
By default, the edge of a given support will be softened by convolution with a 3 pixel wide gaussian. This feature can be turned off by setting the boolean flag to false.
The support can be updated at anytime during reconstruction by calling this method.
Parameters:
object_support The sample support
soften If true, the edges of the support will be softened by covolving it with a 3 pixel wide gaussian. By default this option is off.
Definition at line 95 of file BaseCDI.c++.
References convolve(), nx, ny, and support.
void set_intensity (const Double_2D & detector_intensity)
Set the detector diffraction image (i.e. the square of the amplitude of the wavefield at the detector).
Parameters:
detector_intensity The intensity at the detector
Reimplemented in PartialCharCDI p..
Definition at line 115 of file BaseCDI.c++.
References intensity_sqrt, nx, and ny.
void set_beam_stop (const Double_2D & beam_stop_region)
Set the beam-stop position in the detector plane. This region will be leaf to float when the intensity if scaled during reconstruction. A zero in the array provided represents the beam stop and all other values represent the region which should be scaled.
Parameters:
beam_stop_region The region of the beam stop in the detector plane
Definition at line 109 of file BaseCDI.c++.
References beam_stop, nx, and ny.
void set_relaxation_parameter (double relaxation_parameter) [inline]
Set the relaxation parameters of the reconstruction algorithm. This is $ \beta $ used exactly as it is in Harry's review paper. This maybe reset at anytime during the reconstruction by calling this method. The default value is 0.9.
Parameters:
relaxation_parameter The algorithm relaxation_parameter
Reimplemented in FresnelCDI_WF p..
Definition at line 261 of file BaseCDI.h.
References algorithm, beta, and set_algorithm().
int get_size_x () [inline]
Returns: the number of pixel along the x-axis.
Definition at line 270 of file BaseCDI.h.
References nx.
int get_size_y () [inline]
Returns: the number of pixel along the y-axis.
Definition at line 278 of file BaseCDI.h.
References ny.
void set_algorithm (int alg)
Set the algorithm. By default HIO is used.
Parameters:
alg The algorithm. The options are:
 ER - error reduction
 BIO - basic input-output
 BOO - basic output-output
 HIO - hybrid input-output
 DM - difference map
 SF - solvent-flipping
 ASR - averaged successive reflections
 HPR - hybrid projection reflection
 RAAR - relaxed averaged alternating reflectors
Reimplemented in FresnelCDI_WF p..
Definition at line 189 of file BaseCDI.c++.
References algorithm, beta, and set_custom_algorithm().
void set_custom_algorithm (double m1, double m2, double m3, double m4, double m5, double m6, double m7, double m8, double m9, double m10)
Iterative reconstruction algorithms can be expressed as a combination of the following 5 operators:
$ \hat{P}_S \hat{P}_F$, $\hat{P}_F \hat{P}_S$ , $ \hat{P}_S $ , $ \hat{P}_F $ and $ \hat{I} $
 Where $ \hat{P}_S $ is the support projection and $ \hat{P}_F $ is the intensity projection. These can be combined to form a basis of 10 vectors (see Harray's review). The parameters to this method set the coefficient for each of these vectors. Note: the vector set is linearly dependant.
Please see page 22 of the H.M. Quiney review: TUTORIAL REVIEW, Coherent diffractive imaging using short wavelength light sources, Journal of Modern Optics, 2010, DOI: 10.1080/09500340.2010.495459
Parameters:
m1 Coefficient to the $ [ \hat{P}_S \hat{P}_F - \hat{P}_F \hat{P}_S ]x_k $ term
m2 Coefficient to the $ [ \hat{P}_S \hat{P}_F - \hat{P}_F ]x_k $ term
m3 Coefficient to the $ [ \hat{P}_S \hat{P}_F - \hat{P}_S ]x_k $ term
m4 Coefficient to the $ [ \hat{P}_S \hat{P}_F - \hat{I} ]x_k $ term
m5 Coefficient to the $ [ \hat{P}_F \hat{P}_S - \hat{P}_F ]x_k $ term
m6 Coefficient to the $ [ \hat{P}_F \hat{P}_S - \hat{P}_S ]x_k $ term
m7 Coefficient to the $ [ \hat{P}_F \hat{P}_S - \hat{I} ]x_k $ term
m8 Coefficient to the $ [ \hat{P}_F - \hat{P}_S ]x_k $ term
m9 Coefficient to the $ [ \hat{P}_F - \hat{I} ]x_k $ term
m10 Coefficient to the $ [ \hat{P}_S - \hat{I} ]x_k $ term
Reimplemented in FresnelCDI_WF p..
Definition at line 237 of file BaseCDI.c++.
References algorithm, algorithm_structure, and reallocate_temp_complex_memory().
void print_algorithm ()
Print the current algorithm to standard output. The algorithm is in the form:
 $ x_{k+1} = x_k + (a \hat{P}_S \hat{P}_F + b \hat{P}_F \hat{P}_S + c \hat{P}_S + d \hat{P}_F + e \hat{I} )x_k $
Reimplemented in FresnelCDI_WF p..
Definition at line 275 of file BaseCDI.c++.
References algorithm, and algorithm_structure.
double get_error ()
Get the difference between the estimated diffraction and the actual diffraction pattern.
 $ \chi^2 = \frac { \sum_{pixels} ( M_{pixel} - \sqrt{I_{pixel}} )^2 } { \sum_{pixels} {I_{pixel}} } $.
 Where $ M $ is the magnitude of the current estimate and $ I $ is the measured intensity.
NOTE: This method actually gives you the error for the previous iteration. This is because it's much faster to calculate the error during the intensity scaling step of the iteration rather than performing a FFT just for the error calculation.
Returns: The error metric
Definition at line 123 of file BaseCDI.c++.
References current_error.
static int getAlgFromName (std::string algorithm_name) [inline, static]
Given the name of an algorithm, e.g. `HIO`, return the unique integer identifier. This is used by the configuration file reader, and probably won't be needed by users.
Parameters:
algorithm_name The algorithm name
Returns: The integer identifier
Definition at line 379 of file BaseCDI.h.
References algNameMap.
void apply_shrinkwrap (double gauss_width = 1.5, double threshold = 0.1) [virtual]
Apply the shrinkwrap algorithm. The magnitude of the current ESW estimate will be convolved with a Gaussian, thresholded and set as the new support.
Parameters:
gauss_width The width ($ \sigma $) of the Gaussian in pixels. The default is 1.5.
threshold The threshold which is applied, as a fraction of the maximum pixel value. The default is 0.1 (10%).
Definition at line 413 of file BaseCDI.c++.
References apply_threshold(), complex, convolve(), Complex_2D::get_2d(), MAG, nx, ny, and set_support().
const Double_2D& get_support () [inline]
Get the current support. This might be useful if shrinkwrap has been applied, as it allows you to get the updated support.
Returns: An object reference to the current support.
Definition at line 405 of file BaseCDI.h.
References support.
void apply_support (Complex_2D & c) [virtual]
Apply the support constraint.
Parameters:
c The complex field to apply the support constraint on
Reimplemented in FresnelCDI p..
Definition at line 127 of file BaseCDI.c++.
References TransmissionConstraint::apply_constraint(), support_constraint(), and transmission_constraint.
void project_intensity (Complex_2D & c) [virtual]
Apply the intensity constraint. The ESW is projected to the detector plane, the intensity is scaled to match the measured data and the field is projected back into the sample plane.
Parameters:
c The complex field to apply the intensity constraint on
Definition at line 153 of file BaseCDI.c++.
References propagate_from_detector(), propagate_to_detector(), and scale_intensity().
void scale_intensity (Complex_2D & c) [virtual]
The intensity is scaled to match the measured data. The error is updated in this method.
Parameters:
c The complex field to apply the scaling to
Reimplemented in FresnelCDI p., PartialCharCDI p., and PolyCDI p..
Definition at line 160 of file BaseCDI.c++.
References beam_stop, current_error, Complex_2D::get_mag(), intensity_sqrt, nx, ny, and Complex_2D::set_mag().
virtual void propagate_to_detector (Complex_2D & c) [pure virtual]
Propagate to the sample plane using a fast fourier transform.
Parameters:
c The Complex_2D field to propagate
Implemented in FresnelCDI p., FresnelCDI_WF p., PartialCDI p., PartialCharCDI p., PlanarCDI p., and PolyCDI p..
virtual void propagate_from_detector (Complex_2D & c) [pure virtual]
Propagate to the detector plane using a fast fourier transform.
Parameters:
c The Complex_2D field to propagate
Implemented in FresnelCDI p., FresnelCDI_WF p., PartialCDI p., PartialCharCDI p., PlanarCDI p., and PolyCDI p..
void set_fftw_type (int type)
A flag which is used for the fast fourier transforms to select the fft algorithm. It maybe either FFTW_ESTIMATE, FFTW_MEASURE or FFTW_PATIENT. See the fftw documentation for a description of each. By default we use FFTW_MEASURE. FFTW_ESTIMATE is used for testing purposes.
Parameters:
type - FFTW_ESTIMATE, FFTW_MEASURE or FFTW_PATIENT
Definition at line 491 of file BaseCDI.c++.
References complex, Complex_2D::set_fftw_type(), temp_complex_PF, and temp_complex_PFS.
virtual void set_complex_constraint (TransmissionConstraint & trans_constraint) [inline, virtual]
void set_complex_constraint_function(void (*complex_constraint)(Complex_2D & tranmission)){ custom_complex_constraint = complex_constraint; }
Definition at line 468 of file BaseCDI.h.
References transmission_constraint.
map< string, int > * set_up_algorithm_name_map () [static, protected]
Sets up the mapping between algorithm name and number. This is only called during the initialisation and should not be called elsewhere.
Returns: The algorithm name-iteger mapping
Definition at line 14 of file BaseCDI.c++.
void apply_threshold (Double_2D & array, double threshold) [protected]
Apply a threshold to the values in `array`.
Parameters:
array The array to be thresholded
threshold The threshold which is applied, as a fraction of the maximum pixel value. The default is 0.1 (10%).
Definition at line 474 of file BaseCDI.c++.
References nx.
void convolve (Double_2D & array, double gauss_width, int pixel_cut_off = 4) [protected]
Convolved `array` with a 2-D Gaussian function. To speed up computation we only convolve up to 4 pixels away from the Gaussian peak.
Parameters:
array The array to be convolved
gauss_width The width ($ \sigma $) of the Gaussian in pixels. The default is 1.5.
pixel_cut_off Convolve up to 4 pixels away from the Gaussian peak.
Definition at line 429 of file BaseCDI.c++.
References nx, and ny.
Field Documentation
Complex_2D& complex [protected]
a reference to the Complex_2D object which is altered during each iteration
Definition at line 91 of file BaseCDI.h.
int nx [protected]
The samplings in x
Definition at line 94 of file BaseCDI.h.
int ny [protected]
The samplings in y
Definition at line 97 of file BaseCDI.h.
Complex_2D* temp_complex_PFS [protected]
temporary Complex_2Ds which are used in the computation of the PFS and PF terms for each iteration.
Definition at line 105 of file BaseCDI.h.
double beta [protected]
the relaxation parameter
Reimplemented in PolyCDI p..
Definition at line 111 of file BaseCDI.h.
Double_2D support [protected]
a copy of the support
Definition at line 114 of file BaseCDI.h.
Double_2D intensity_sqrt [protected]
a copy of the square root of the intensity at the detector plane.
Definition at line 117 of file BaseCDI.h.
Double_2D* beam_stop [protected]
A mask of the beam-stop which is used when scaling the intensity
Definition at line 120 of file BaseCDI.h.
int algorithm [protected]
the algorithm which is being used: ER, HIO etc.
Definition at line 123 of file BaseCDI.h.
double algorithm_structure[NTERMS] [protected]
an array which holds the structure of the algorithm. i.e. the coefficients for each term in the iteration equation.
Definition at line 127 of file BaseCDI.h.
double current_error [protected]
the difference between the intensity in the detector plane the current estimated intensity.
Definition at line 131 of file BaseCDI.h.
int n_best [protected]
how many best estimates to store
Definition at line 134 of file BaseCDI.h.
Complex_2D** best_array [protected]
array of the best estimates
Definition at line 137 of file BaseCDI.h.
double* best_error_array [protected]
array of the error corresponding to each of the best estimates
Definition at line 141 of file BaseCDI.h.
TransmissionConstraint* transmission_constraint [protected]
a function pointer to a cumstomized complex constraint
Definition at line 145 of file BaseCDI.h.
map< string, int > * algNameMap = BaseCDI::set_up_algorithm_name_map() [static, protected]
a mapping between the algorithm name (string) and identification number
Definition at line 149 of file BaseCDI.h.
The documentation for this class was generated from the following files:
BaseCDI.h
BaseCDI.c++