FresnelCDI_WF Class Reference
The class which performs Fresnel CDI white field reconstruction.
#include <FresnelCDI_WF.h>
Public Member Functions
FresnelCDI_WF (Complex_2D &initial_guess, double beam_wavelength, double zone_focal_length, double focal_detector_length, double pixel_size, int n_best=1)
virtual ~FresnelCDI_WF ()
int iterate ()
virtual void propagate_from_detector (Complex_2D &c)
virtual void propagate_to_detector (Complex_2D &c)
virtual void initialise_estimate (int seed=0)
virtual void set_support (double z_diameter, double size=1.01)
void set_algorithm (int alg)
void print_algorithm ()
void set_relaxation_parameter (double relaxation_parameter)
void set_custom_algorithm (double m1, double m2, double m3, double m4, double m5, double m6, double m7, double m8, double m9, double m10)
void multiply_factors (Complex_2D &c, int direction)
Complex_2D * get_best_result (double &error, int index=0)
void set_support (const Double_2D &object_support, bool soften=false)
void set_intensity (const Double_2D &detector_intensity)
void set_beam_stop (const Double_2D &beam_stop_region)
int get_size_x ()
int get_size_y ()
const Complex_2D & get_exit_surface_wave ()
void set_exit_surface_wave (Complex_2D &esw)
double get_error ()
virtual void apply_shrinkwrap (double gauss_width=1.5, double threshold=0.1)
const Double_2D & get_support ()
virtual void apply_support (Complex_2D &c)
virtual void project_intensity (Complex_2D &c)
virtual void scale_intensity (Complex_2D &c)
void set_fftw_type (int type)
virtual void set_complex_constraint (TransmissionConstraint &trans_constraint)
void reset_best ()
Static Public Member Functions
static int getAlgFromName (std::string algorithm_name)
Protected Member Functions
void apply_threshold (Double_2D &array, double threshold)
void convolve (Double_2D &array, double gauss_width, int pixel_cut_off=4)
void support_constraint (Complex_2D &c)
void reallocate_temp_complex_memory ()
void update_n_best ()
Static Protected Member Functions
static std::map< std::string, int > * set_up_algorithm_name_map ()
Protected Attributes
double wavelength
double zone_to_focal_length
double focal_to_detector_length
double pixel_length
Complex_2D coefficient
Complex_2D & complex
int nx
int ny
Complex_2D * temp_complex_PFS
Complex_2D * temp_complex_PF
Complex_2D * temp_complex_PS
Complex_2D * temp_complex_PSF
double beta
Double_2D support
Double_2D intensity_sqrt
Double_2D * beam_stop
int algorithm
double algorithm_structure [NTERMS]
double current_error
int n_best
Complex_2D ** best_array
double * best_error_array
TransmissionConstraint * transmission_constraint
Static Protected Attributes
static std::map< std::string, int > * algNameMap = BaseCDI::set_up_algorithm_name_map()
Detailed Description
Author: Nadia Davidson <nadiamd@unimelb.edu.au> Last modified on 7/1/2011
This is the class used for reconstructing white-field data prior to running Fresnel reconstruction with FresnelCDI. It inherits most methods from BaseCDI, so please look at the documentation of this class also. Although there are some differences in the underlying code between this class and the planar case, the interface is generally unchanged. Therefore users should refer to the instructions for BaseCDI to understand how to use a FresnelCDI_WF object in their own code. Only the differences relevant to users will be documented here.
Definition at line 31 of file FresnelCDI_WF.h.
Constructor & Destructor Documentation
FresnelCDI_WF (Complex_2D & initial_guess, double beam_wavelength, double zone_focal_length, double focal_detector_length, double pixel_size, int n_best = 1)
Create a FresnelCDI_WF object. All of the dimensions which are given as input should be in the same units. e.g metres.
Parameters:
initial_guess The complex 2-D field which is modified by this object. This represents the illuminating white-field in the detector plane. It may be pre-initialised to a best first guess (e.g manually); it may be loaded from a file (e.g. the output from a previous reconstruction job); or it may be unitialised, and the default initialisation provided by FresnelCDI_WF may be used.
beam_wavelength Wavelength of the beam
zone_focal_length The distance from the zone plate to the focal point
focal_detector_length The distance from the focal point to the detector
pixel_size The diameter of one of the detector pixels.
Double_2D result(nx,ny); forward_coefficients_const->get_2d(PHASE,result); write_ppm(`forward_coefficients_phase.ppm`,result);
Definition at line 17 of file FresnelCDI_WF.c++.
References coefficient, focal_to_detector_length, BaseCDI::nx, BaseCDI::ny, pixel_length, Complex_2D::set_imag(), Complex_2D::set_real(), and zone_to_focal_length.
virtual ~FresnelCDI_WF () [inline, virtual]
The destructor for this class
Definition at line 86 of file FresnelCDI_WF.h.
Member Function Documentation
int iterate () [virtual]
The iterate() method of BaseCDI is overridden here with 3-plane propagation.
Reimplemented from BaseCDI p..
Definition at line 122 of file FresnelCDI_WF.c++.
References BaseCDI::apply_support(), BaseCDI::complex, propagate_from_detector(), propagate_to_detector(), BaseCDI::scale_intensity(), and SUCCESS.
void propagate_from_detector (Complex_2D & c) [virtual]
Propagate to the zone plate plane using the paraxial free-space equation.
Parameters:
c The Complex_2D field to propagate
Implements BaseCDI p..
Definition at line 152 of file FresnelCDI_WF.c++.
References Complex_2D::invert(), multiply_factors(), and Complex_2D::perform_backward_fft().
void propagate_to_detector (Complex_2D & c) [virtual]
Propagate to the detector plane using the paraxial free-space equation.
Parameters:
c The Complex_2D field to propagate
Implements BaseCDI p..
Definition at line 164 of file FresnelCDI_WF.c++.
References Complex_2D::invert(), multiply_factors(), and Complex_2D::perform_forward_fft().
void initialise_estimate (int seed = 0) [virtual]
This method overrides the one in BaseCDI. The white-field is initialised to be zero outside the support (note that we assume here that the support for the zone plate is approx. the same size and shape as the support region of the white-field in the detector plane. Inside the support region, the real component is set to the random number and the imaginary component is set to zero (this makes the reconstruction much fast than it would be if both components were random).
Parameters:
seed The seed for the random number generator
Implements BaseCDI p..
Definition at line 99 of file FresnelCDI_WF.c++.
References BaseCDI::complex, IMAG, BaseCDI::intensity_sqrt, BaseCDI::nx, BaseCDI::ny, REAL, Complex_2D::set_value(), and BaseCDI::support.
void set_support (double z_diameter, double size = 1.01) [virtual]
This method is an alternative to setting the support using an image. You should pass the zone-plate diameter and (optionally) how much bigger the support should be than the zone-plate. The support will be set to a circle, centered at the center of the zone-plate plane, with a diameter equal to the zone plate diameter time the size parameter. The support edge is softened by convoluting it with a gaussian function (width=3 pixels).
Parameters:
z_diameter Diameter of the zone-plate (given in the same units as the dimensions given to the constructed).
size What proportion of the zone-plate plane will be used for the support, by default this is 1.01 (the support is 1% larger than the support in diameter).
Definition at line 177 of file FresnelCDI_WF.c++.
References BaseCDI::convolve(), focal_to_detector_length, BaseCDI::nx, BaseCDI::ny, pixel_length, BaseCDI::support, and zone_to_focal_length.
void set_algorithm (int alg) [inline]
This method is not available for FresnelCDI_WF.
Reimplemented from BaseCDI p..
Definition at line 147 of file FresnelCDI_WF.h.
void print_algorithm () [inline]
This method is not available for FresnelCDI_WF.
Reimplemented from BaseCDI p..
Definition at line 155 of file FresnelCDI_WF.h.
void set_relaxation_parameter (double relaxation_parameter) [inline]
This method is not available for FresnelCDI_WF.
Reimplemented from BaseCDI p..
Definition at line 164 of file FresnelCDI_WF.h.
void set_custom_algorithm (double m1, double m2, double m3, double m4, double m5, double m6, double m7, double m8, double m9, double m10) [inline]
This method is not available for FresnelCDI_WF.
Reimplemented from BaseCDI p..
Definition at line 175 of file FresnelCDI_WF.h.
Complex_2D * get_best_result (double & error, int index = 0) [inherited]
While the reconstruction is running this object will store the `n_best` number of best estimates according to the error metric. So, for example, if HIO is used and the error enters and leaves an error minima during reconstruction, the best (ie. lowest error) Complex_2D results will be kept. They can then be retrieved using this method.
Parameters:
index get best result number `index`. 0 is the best, 1 is the 2nd best etc...
error `error` is filled with the metric error of the selected best result
Definition at line 82 of file BaseCDI.c++.
References BaseCDI::best_array, BaseCDI::best_error_array, and BaseCDI::n_best.
void set_support (const Double_2D & object_support, bool soften = false) [inherited]
Set the sample support. A `0` value in the Double_2D is interpreted as being outside the support. Pixels with the maximum value of the Double_2D are considered inside the support. Values between 0 and the maximum indict the soft edge of the support. In this case, when the support is applied, the esw magnitude is scaled relative to the support edge value.
By default, the edge of a given support will be softened by convolution with a 3 pixel wide gaussian. This feature can be turned off by setting the boolean flag to false.
The support can be updated at anytime during reconstruction by calling this method.
Parameters:
object_support The sample support
soften If true, the edges of the support will be softened by covolving it with a 3 pixel wide gaussian. By default this option is off.
Definition at line 95 of file BaseCDI.c++.
References BaseCDI::convolve(), BaseCDI::nx, BaseCDI::ny, and BaseCDI::support.
void set_intensity (const Double_2D & detector_intensity) [inherited]
Set the detector diffraction image (i.e. the square of the amplitude of the wavefield at the detector).
Parameters:
detector_intensity The intensity at the detector
Reimplemented in PartialCharCDI p..
Definition at line 115 of file BaseCDI.c++.
References BaseCDI::intensity_sqrt, BaseCDI::nx, and BaseCDI::ny.
void set_beam_stop (const Double_2D & beam_stop_region) [inherited]
Set the beam-stop position in the detector plane. This region will be leaf to float when the intensity if scaled during reconstruction. A zero in the array provided represents the beam stop and all other values represent the region which should be scaled.
Parameters:
beam_stop_region The region of the beam stop in the detector plane
Definition at line 109 of file BaseCDI.c++.
References BaseCDI::beam_stop, BaseCDI::nx, and BaseCDI::ny.
int get_size_x () [inline, inherited]
Returns: the number of pixel along the x-axis.
Definition at line 270 of file BaseCDI.h.
References BaseCDI::nx.
int get_size_y () [inline, inherited]
Returns: the number of pixel along the y-axis.
Definition at line 278 of file BaseCDI.h.
References BaseCDI::ny.
double get_error () [inherited]
Get the difference between the estimated diffraction and the actual diffraction pattern.
 $ \chi^2 = \frac { \sum_{pixels} ( M_{pixel} - \sqrt{I_{pixel}} )^2 } { \sum_{pixels} {I_{pixel}} } $.
 Where $ M $ is the magnitude of the current estimate and $ I $ is the measured intensity.
NOTE: This method actually gives you the error for the previous iteration. This is because it's much faster to calculate the error during the intensity scaling step of the iteration rather than performing a FFT just for the error calculation.
Returns: The error metric
Definition at line 123 of file BaseCDI.c++.
References BaseCDI::current_error.
static int getAlgFromName (std::string algorithm_name) [inline, static, inherited]
Given the name of an algorithm, e.g. `HIO`, return the unique integer identifier. This is used by the configuration file reader, and probably won't be needed by users.
Parameters:
algorithm_name The algorithm name
Returns: The integer identifier
Definition at line 379 of file BaseCDI.h.
References BaseCDI::algNameMap.
void apply_shrinkwrap (double gauss_width = 1.5, double threshold = 0.1) [virtual, inherited]
Apply the shrinkwrap algorithm. The magnitude of the current ESW estimate will be convolved with a Gaussian, thresholded and set as the new support.
Parameters:
gauss_width The width ($ \sigma $) of the Gaussian in pixels. The default is 1.5.
threshold The threshold which is applied, as a fraction of the maximum pixel value. The default is 0.1 (10%).
Definition at line 413 of file BaseCDI.c++.
References BaseCDI::apply_threshold(), BaseCDI::complex, BaseCDI::convolve(), Complex_2D::get_2d(), MAG, BaseCDI::nx, BaseCDI::ny, and BaseCDI::set_support().
const Double_2D& get_support () [inline, inherited]
Get the current support. This might be useful if shrinkwrap has been applied, as it allows you to get the updated support.
Returns: An object reference to the current support.
Definition at line 405 of file BaseCDI.h.
References BaseCDI::support.
void apply_support (Complex_2D & c) [virtual, inherited]
Apply the support constraint.
Parameters:
c The complex field to apply the support constraint on
Reimplemented in FresnelCDI p..
Definition at line 127 of file BaseCDI.c++.
References TransmissionConstraint::apply_constraint(), BaseCDI::support_constraint(), and BaseCDI::transmission_constraint.
void project_intensity (Complex_2D & c) [virtual, inherited]
Apply the intensity constraint. The ESW is projected to the detector plane, the intensity is scaled to match the measured data and the field is projected back into the sample plane.
Parameters:
c The complex field to apply the intensity constraint on
Definition at line 153 of file BaseCDI.c++.
References BaseCDI::propagate_from_detector(), BaseCDI::propagate_to_detector(), and BaseCDI::scale_intensity().
void scale_intensity (Complex_2D & c) [virtual, inherited]
The intensity is scaled to match the measured data. The error is updated in this method.
Parameters:
c The complex field to apply the scaling to
Reimplemented in FresnelCDI p., PartialCharCDI p., and PolyCDI p..
Definition at line 160 of file BaseCDI.c++.
References BaseCDI::beam_stop, BaseCDI::current_error, Complex_2D::get_mag(), BaseCDI::intensity_sqrt, BaseCDI::nx, BaseCDI::ny, and Complex_2D::set_mag().
void set_fftw_type (int type) [inherited]
A flag which is used for the fast fourier transforms to select the fft algorithm. It maybe either FFTW_ESTIMATE, FFTW_MEASURE or FFTW_PATIENT. See the fftw documentation for a description of each. By default we use FFTW_MEASURE. FFTW_ESTIMATE is used for testing purposes.
Parameters:
type - FFTW_ESTIMATE, FFTW_MEASURE or FFTW_PATIENT
Definition at line 491 of file BaseCDI.c++.
References BaseCDI::complex, Complex_2D::set_fftw_type(), BaseCDI::temp_complex_PF, and BaseCDI::temp_complex_PFS.
virtual void set_complex_constraint (TransmissionConstraint & trans_constraint) [inline, virtual, inherited]
void set_complex_constraint_function(void (*complex_constraint)(Complex_2D & tranmission)){ custom_complex_constraint = complex_constraint; }
Definition at line 468 of file BaseCDI.h.
References BaseCDI::transmission_constraint.
map< string, int > * set_up_algorithm_name_map () [static, protected, inherited]
Sets up the mapping between algorithm name and number. This is only called during the initialisation and should not be called elsewhere.
Returns: The algorithm name-iteger mapping
Definition at line 14 of file BaseCDI.c++.
void apply_threshold (Double_2D & array, double threshold) [protected, inherited]
Apply a threshold to the values in `array`.
Parameters:
array The array to be thresholded
threshold The threshold which is applied, as a fraction of the maximum pixel value. The default is 0.1 (10%).
Definition at line 474 of file BaseCDI.c++.
References BaseCDI::nx.
void convolve (Double_2D & array, double gauss_width, int pixel_cut_off = 4) [protected, inherited]
Convolved `array` with a 2-D Gaussian function. To speed up computation we only convolve up to 4 pixels away from the Gaussian peak.
Parameters:
array The array to be convolved
gauss_width The width ($ \sigma $) of the Gaussian in pixels. The default is 1.5.
pixel_cut_off Convolve up to 4 pixels away from the Gaussian peak.
Definition at line 429 of file BaseCDI.c++.
References BaseCDI::nx, and BaseCDI::ny.
Field Documentation
double wavelength [protected]
the beam wavelength
Definition at line 36 of file FresnelCDI_WF.h.
double zone_to_focal_length [protected]
the distance from the zone plate to the focal point
Definition at line 39 of file FresnelCDI_WF.h.
double focal_to_detector_length [protected]
the distance from the focal point to the detector
Definition at line 42 of file FresnelCDI_WF.h.
double pixel_length [protected]
the pixel size
Definition at line 45 of file FresnelCDI_WF.h.
Complex_2D coefficient [protected]
an array which holds a constants we use when propagating between difference planes
Definition at line 49 of file FresnelCDI_WF.h.
Complex_2D& complex [protected, inherited]
a reference to the Complex_2D object which is altered during each iteration
Definition at line 91 of file BaseCDI.h.
int nx [protected, inherited]
The samplings in x
Definition at line 94 of file BaseCDI.h.
int ny [protected, inherited]
The samplings in y
Definition at line 97 of file BaseCDI.h.
Complex_2D* temp_complex_PFS [protected, inherited]
temporary Complex_2Ds which are used in the computation of the PFS and PF terms for each iteration.
Definition at line 105 of file BaseCDI.h.
double beta [protected, inherited]
the relaxation parameter
Reimplemented in PolyCDI p..
Definition at line 111 of file BaseCDI.h.
Double_2D support [protected, inherited]
a copy of the support
Definition at line 114 of file BaseCDI.h.
Double_2D intensity_sqrt [protected, inherited]
a copy of the square root of the intensity at the detector plane.
Definition at line 117 of file BaseCDI.h.
Double_2D* beam_stop [protected, inherited]
A mask of the beam-stop which is used when scaling the intensity
Definition at line 120 of file BaseCDI.h.
int algorithm [protected, inherited]
the algorithm which is being used: ER, HIO etc.
Definition at line 123 of file BaseCDI.h.
double algorithm_structure[NTERMS] [protected, inherited]
an array which holds the structure of the algorithm. i.e. the coefficients for each term in the iteration equation.
Definition at line 127 of file BaseCDI.h.
double current_error [protected, inherited]
the difference between the intensity in the detector plane the current estimated intensity.
Definition at line 131 of file BaseCDI.h.
int n_best [protected, inherited]
how many best estimates to store
Definition at line 134 of file BaseCDI.h.
Complex_2D** best_array [protected, inherited]
array of the best estimates
Definition at line 137 of file BaseCDI.h.
double* best_error_array [protected, inherited]
array of the error corresponding to each of the best estimates
Definition at line 141 of file BaseCDI.h.
TransmissionConstraint* transmission_constraint [protected, inherited]
a function pointer to a cumstomized complex constraint
Definition at line 145 of file BaseCDI.h.
map< string, int > * algNameMap = BaseCDI::set_up_algorithm_name_map() [static, protected, inherited]
a mapping between the algorithm name (string) and identification number
Definition at line 149 of file BaseCDI.h.
The documentation for this class was generated from the following files:
FresnelCDI_WF.h
FresnelCDI_WF.c++