PhaseDiverseCDI Class Reference
The class which performs phase diverse and ptychographic reconstruction.
#include <PhaseDiverseCDI.h>
Public Types
CROSS_CORRELATION
MINIMUM_ERROR
enum { CROSS_CORRELATION,
MINIMUM_ERROR
 }
Public Member Functions
PhaseDiverseCDI (double beta=1.0, double gamma=1.0, bool parallel=false, int granularity=1)
~PhaseDiverseCDI ()
void add_new_position (BaseCDI *local, double x=0, double y=0, double alpha=1)
void initialise_estimate ()
void iterate ()
void set_iterations_per_cycle (int iterations)
void set_feedback_parameter (double beta)
void set_amplification_factor (double gamma)
void set_probe_scaling (int n_probe, double alpha)
Complex_2D * get_transmission ()
void set_transmission (Complex_2D &new_transmission)
void adjust_positions (int type=CROSS_CORRELATION, bool forwards=true, int x_min=-50, int x_max=+50, int y_min=-50, int y_max=+50, double step_size=4)
double get_final_x_position (int n_probe)
double get_final_y_position (int n_probe)
Protected Attributes
std::vector< BaseCDI * > singleCDI
std::vector< Complex_2D * > single_result
std::vector< Double_2D * > weights
std::vector< double > x_position
std::vector< double > y_position
double beta
double gamma
std::vector< double > alpha
Complex_2D * object
int iterations_per_cycle
int scale
int nx
int ny
int x_min
int y_min
bool parallel
bool weights_set
Private Member Functions
void add_to_object (int n_probe)
void update_from_object (int n_probe)
void get_result (BaseCDI *local, Complex_2D &result)
void set_result (BaseCDI *local, Complex_2D &result)
void reallocate_object_memory (int new_nx, int new_ny)
void scale_object (double factor)
void set_up_weights ()
int check_position (int n_probe, double step_size=4, int min_x=-50, int max_x=50, int min_y=-50, int max_y=50, int tries=0)
int get_global_x_pos (int x, double x_offset)
int get_global_y_pos (int y, double y_offset)
int get_local_x_pos (int x, double x_offset)
int get_local_y_pos (int y, double y_offset)
Detailed Description
Author: Nadia Davidson <nadiamd@unimelb.edu.au>
This class can be used to perform phase diverse or ptychographic reconstruction of either Fresnel or plane-wave CDI data. Any number of frames (also called local/single frames or probes in this documentation) may be added to the reconstruction. In order to perform a reconstruction, you will need to create either a new FresnelCDI or PlanarCDI object for each of these 'local' datasets. The FresnelCDI or PlanarCDI objects must then be passed to a PhaseDiverseCDI object. Because the each sub-iteration (ie. each iteration of a local frame) is performed using the code in FresnelCDI/PlanarCDI, all the functionality available in these classes is also available here. For example complex constraint can be set, shrink-wrap can be used, the estimate can be initialised using the results from a previous reconstruction etc. An example can be found in the /examples directory, demonstrating how to use PhaseDiverseCDI.
The displacement in position between 'local' frames may be either transverse to the beam direction, or longitudinal, along the beam direction. The longitudinal position (for FresnelCDI) is set when the FresnelCDI objects are initially constructed. Transverse positions are set when the FresnelCDI/PlanarCDI objects are added to the PhaseDiverseCDI object. This class allows the transverse positions to be automatically adjusted during reconstruction using the `adjust_positions` function.
The code allows for several options in the type of reconstruction which is done:
The reconstruction can be performed in series or parallel.
In the case of series (see for example the paper....), a 'local' frame will undergo one or more iterations, the result will be updated to a 'global' estimate of the sample, and this estimate will form the starting point for the next frame. For each call to the method `iterate()` this process is repeated until each local frame is used once. The algorithm can be described by:
 $ T_{k+1} = (1-\beta w^n)T_k + \beta w^n T^n_k$
 where $T_{k+1}$ is the updated global function, $T^n$ is the updated local function for the nth local frame. $\beta$ is the relaxation parameter and the weight is $ w^n(\rho) = \alpha^n (\frac{|T^n(\rho)|}{max|T^n(\rho)|} )^\gamma $ for Fresnel CDI or $w^n = \alpha^n$ for Plane-wave CDI. The weight is zero outside of the support.
For a parallel reconstruction (see .....), each frame with independently undergo one of more iteration, the result from all frames will be merged to form a new estimate of the sample, this estimate then becomes the starting point for the next iteration of all frames. The algorithm can be described by:
 $ T_{k+1} = (1-\beta)T_k + \beta \sum_n(w^n T^n_k)$
 where $T_{k+1}$, $T^n$, and $\beta$ were defined earlier. The weight, w, is similar to that used for series reconstruction, but the weight it normalised such that $ \sum_n w^n = 1 $. i.e. $ w^n_{parallel}= w^n_{series} / \sum_n w^n_{series} $
The number of local iterations to perform before updating the result to the 'global' function can be set.
The feedback parameter, beta, may be set. This quantity is used to set how much of the previous 'global' sample function will be left after the next 'global' iteration.
The amplification factor, gamma, and the probe scaling, alpha, may also be see. These parameters control the weighting of one frame (and pixels within a frame) with respect to each other.
Definition at line 94 of file PhaseDiverseCDI.h.
Constructor & Destructor Documentation
PhaseDiverseCDI (double beta = 1.0, double gamma = 1.0, bool parallel = false, int granularity = 1)
Construct a PhaseDiverseCDI object for phase diverse or ptychographic reconstruction. The data should be entered later using the 'add_new_position' function.
Parameters:
beta The feedback parameter. By default this is 1 (no feedback).
gamma The amplification factor. By default this is 1 (no amplification).
parallel true - run in parallel mode, false - run in series mode. By default series mode is set.
granularity A factor which controls sub-pixel alignment. 1 = regular, 2 = 2 'global' pixels for every 1 'local' pixel. i.e. 2 allows alignment to within half a pixel. NOTE: This is not currently working properly!
Definition at line 27 of file PhaseDiverseCDI.c++.
~PhaseDiverseCDI ()
Destructor for PhaseDiverseCDI
Definition at line 47 of file PhaseDiverseCDI.c++.
References object, single_result, and weights.
Member Function Documentation
void initialise_estimate ()
Initialise the estimate of the 'global' object function. The initialisation is performed using the current estimate for each 'local' frame. For this reason you must first initialise each FresnelCDI/PlanarCDI object individually before calling this function.
Definition at line 174 of file PhaseDiverseCDI.c++.
References add_to_object(), nx, ny, object, Complex_2D::set_imag(), Complex_2D::set_real(), and singleCDI.
void iterate ()
Perform one iteration. This with involve performing one or more iterations for each sub-set of data. The exact implementation depends on whether the reconstruction is being run in series or parallel mode.
static bool flag = false; if(!flag){ char buf[50]; Double_2D result(nx,ny); Complex_2D trans(nx,ny); sprintf(buf,`itr_%i_%i_1.tiff`,i,j); ((FresnelCDI*)singleCDI.at(i))->get_transmission_function(trans); trans.copy(*get_transmission()); trans.get_2d(MAG,result); write_image(buf,result,false,0,1.0); flag=true; }
Definition at line 194 of file PhaseDiverseCDI.c++.
References add_to_object(), beta, iterations_per_cycle, parallel, scale_object(), singleCDI, and update_from_object().
void set_iterations_per_cycle (int iterations) [inline]
Set the number of 'local' frame iterations before updating the result to the 'global' object function.
Parameters:
iterations The number of 'local' iterations.
Definition at line 209 of file PhaseDiverseCDI.h.
References iterations_per_cycle.
void set_feedback_parameter (double beta) [inline]
Set the feed-back parameter.
Parameters:
beta The feedback parameter
Definition at line 218 of file PhaseDiverseCDI.h.
References weights_set.
Complex_2D * get_transmission ()
This function allows you to access the 'global' sample function.
Returns: The current estimate of either the transmission (for FresnelCDI) or exit-surface-wave (for PlanarCDI)
Definition at line 80 of file PhaseDiverseCDI.c++.
References object.
void set_transmission (Complex_2D & new_transmission)
Set the 'global' sample function. This method could be used, for example, instead of 'initialise_estimate' to initialise the results to those from a previous reconstruction.
Parameters:
new_transmission The transmission (for FresnelCDI) or exit-surface-wave (for PlanarCDI) to copy.
Definition at line 88 of file PhaseDiverseCDI.c++.
References Complex_2D::copy(), Complex_2D::get_size_x(), Complex_2D::get_size_y(), nx, ny, object, and reallocate_object_memory().
void adjust_positions (int type = CROSS_CORRELATION, bool forwards = true, int x_min = -50, int x_max = +50, int y_min = -50, int y_max = +50, double step_size = 4)
Align the frames with respect to each other. The transverse positions will be automatically adjusted and the new positions used for the remainder of the reconstruction run. If needed, the new positions can be retrieved using the `get_final_x(y)_position` functions.
Two methods to align the frames are provided:
PhaseDiverse::CROSS_CORRELATION - implements the cross-correlation method using the magnitude of the transmission/exit-surface-wave. There is pleanty of documentation describing how cross-correlation can be used for alignment. see http://en.wikipedia.org/wiki/Cross-correlation for example. We use the fourier transform implementation. This method is useful if the relative positions are unknown to great than 10 pixels. It is also much faster than the alternative.
PhaseDiverse::MINIMUM_ERROR - aligns the frames by looking for the position which gives the smallest error in the detector plane. The error metric is described in PlanarCDI.h. The algorithm works by checking the error in the 9 positions centered on the current positions: (x-step_size, y-step_size), (x, y-step_size), (x+step_size, y-step_size), (x-step_size, y) etc. Where `step_size` is an input parameter which has a default of 4 pixels. The position with the minimum error becomes the new position, the step_size is decreased to half, and the procedure is repeated. The algorithm ends when the step size is less than a pixel. This method of frame alignment is good for small refinement, but is less reliable if the relative differences are not known to within about 10-20 pixels. It is also significatly slower.
Parameters:
type either PhaseDiverse::CROSS_CORRELATION or PhaseDiverse::MINIMUM_ERROR. PhaseDiverse::CROSS_CORRELATION is the default.
forwards By default the alignment is done in order of the frames, with the second being aligned the the first, followed by the third to the second and so on. In you needed to run the alignment in reverse e.g. aligning initially to the last frame, then this parameter should be false. You might use this, for example, if you want to check that the alignment is consistent in both forward and backward directions.
x_min Positions below x+x_min pixels are not allowed. For PhaseDiverse::CROSS_CORRELATION, the algorithm will only search within the range x+x_min to x+x_max. For PhaseDiverse::MINIMUM_ERROR, if a position below x_min is encountered, the algorithm aborts and returns the positions to their original value.
x_max See x_min.
y_min See y_min.
y_max See y_max.
step_size The initial step size to use in the case of PhaseDiverse::MINIMUM_ERROR.
if(!parallel){ parallel = true; weights_set=false; for(int i=0; i<10; i++) iterate(); }
char name[80]; Double_2D pic(nx,ny); object->get_2d(MAG,pic); sprintf(name,`pic_%i.tiff`,n); write_image(name,pic,false, 0,1);
static int counter = 0; char buff[90]; sprintf(buff,`temp_single_%i.tiff`,counter); write_image(buff,*temp_single_int,false); cout << `not here`<<endl;
sprintf(buff,`temp_object_%i.tiff`,counter); write_image(buff,temp_others,false); counter++;
cout << `moving prob ` << n << ` from (` << before_x << `,` << before_y << `) ` << ` $\rightarrow$ (` << x_position.at(n) << `,` << y_position.at(n) << `).` << endl;
for(int i=0; i<singleCDI.size(); i++){ add_to_object(i); }
Definition at line 329 of file PhaseDiverseCDI.c++.
References add_to_object(), beta, check_position(), Complex_2D::get_imag(), Complex_2D::get_mag(), Complex_2D::get_real(), get_result(), nx, ny, object, parallel, scale, Complex_2D::set_imag(), Complex_2D::set_real(), single_result, singleCDI, weights_set, x_min, x_position, y_min, and y_position.
double get_final_x_position (int n_probe) [inline]
Get the current position of the 'n_probe'th frame.
Parameters:
n_probe The index of the frame you wish to retrieve the position for. 0=the first frame you added, 1=2nd frame added etc....
Returns: the transverse horizontal position
Definition at line 330 of file PhaseDiverseCDI.h.
References x_position.
double get_final_y_position (int n_probe) [inline]
Get the current position of the 'n_probe'th frame.
Parameters:
n_probe The index of the frame you wish to retrieve the position for. 0=the first frame you added, 1=2nd frame added etc....
Returns: the transverse vertical position
Definition at line 341 of file PhaseDiverseCDI.h.
References y_position.
void add_to_object (int n_probe) [private]
Update a 'local' frame result to the 'global' object. The result is weighted before being added.
Parameters:
n_probe The local frame number.
Double_2D temp(nx,ny); object->get_2d(MAG,temp); write_image(`before_norm.tiff`,temp,false,0,1);
normalise if(scale!=1){ for(int i_=1; i_< lnx-1; i_++){ for(int j_=1; j_< lny-1; j_++){
double weight = this_weight.get(i_,j_);
don't even bother to do anything is the weight at this pixel is zero. if(weight!=0){
get the pixel positions in the global (object) frame. int i = get_global_x_pos(i_,x_offset)*scale; int j = get_global_y_pos(j_,y_offset)*scale;
bounds check if(i>=0&&j>=0&&i<nx&&j<ny){
double weight_r = 0; double weight_i = 0;
for(int di=0; di < scale; di++){ for(int dj=0; dj < scale; dj++){ add to the sum for each pixel so we can normalise later weight_r+=object->get_real(i+di,j+dj); weight_i+=object->get_imag(i+di,j+dj); } }
cout << weight_i << ` ` << small->get_imag(i_,j_) << ` `; if(weight_r!=0&&weight_i!=0){ weight_r=small->get_real(i_,j_)*scale*scale/weight_r; weight_i=small->get_imag(i_,j_)*scale*scale/weight_i;
cout << weight_i <<endl;
for(int di=0; di < scale; di++){ for(int dj=0; dj < scale; dj++){ object->set_real(i+di,j+dj,weight_r*object->get_real(i+di,j+dj)); object->set_imag(i+di,j+dj,weight_i*object->get_imag(i+di,j+dj)); } } } } } } } }
Definition at line 843 of file PhaseDiverseCDI.c++.
References get_global_x_pos(), get_global_y_pos(), Complex_2D::get_imag(), Complex_2D::get_real(), get_result(), Complex_2D::get_size_x(), Complex_2D::get_size_y(), nx, ny, object, parallel, scale, Complex_2D::set_imag(), Complex_2D::set_real(), set_up_weights(), single_result, singleCDI, weights, x_min, x_position, y_min, and y_position.
void update_from_object (int n_probe) [private]
Update a 'local' frame result from the 'global' object.
Parameters:
n_probe The local frame number.
Definition at line 1058 of file PhaseDiverseCDI.c++.
References get_global_x_pos(), get_global_y_pos(), Complex_2D::get_imag(), Complex_2D::get_real(), Complex_2D::get_size_x(), Complex_2D::get_size_y(), nx, ny, object, scale, Complex_2D::set_imag(), Complex_2D::set_real(), set_result(), set_up_weights(), single_result, singleCDI, weights, x_position, and y_position.
void get_result (BaseCDI * local, Complex_2D & result) [private]
This function is basically a wrapper to check the BaseCDI type so that the correct type of sample function is retrieve (either transmission function or the exit-surface-wave.
Parameters:
local A pointer to either a PlanarCDI or FresnelCDI object
Returns: result The estimate is copied from local to result
Definition at line 309 of file PhaseDiverseCDI.c++.
References Complex_2D::copy().
void set_result (BaseCDI * local, Complex_2D & result) [private]
This function is basically a wrapper to check the BaseCDI type so that the correct type of sample function is set (either transmission function or the exit-surface-wave.
Parameters:
local A pointer to either a PlanarCDI or FresnelCDI object
Returns: result The estimate is copied from result to local
Definition at line 318 of file PhaseDiverseCDI.c++.
void reallocate_object_memory (int new_nx, int new_ny) [private]
This function is used to reallocate memory for the 'global' sample object. It is only used when add_new_position is called, in the case that the frame does not fit within the bounds of the current object array.
Definition at line 67 of file PhaseDiverseCDI.c++.
References nx, ny, and object.
void scale_object (double factor) [private]
This function is used during reconstruction in parallel mode. It is similar to simply scaling all the elements of the 'global' sample array, (e.g. with object.scale(factor). However, this method preserves the value of the elements outside the boundary of the sample. ie. it checks the weights of all the local frames to work out which area to scale.
Parameters:
factor The scaled elements go from 'a' to 'factor*a'.
Definition at line 262 of file PhaseDiverseCDI.c++.
References Complex_2D::get_imag(), get_local_x_pos(), get_local_y_pos(), Complex_2D::get_real(), nx, ny, object, scale, Complex_2D::set_imag(), Complex_2D::set_real(), set_up_weights(), singleCDI, weights, x_position, and y_position.
void set_up_weights () [private]
Calculate the weights for each frame in the reconstruction. See a description above for how they are set.
Definition at line 713 of file PhaseDiverseCDI.c++.
References alpha, beta, gamma, Complex_2D::get_2d(), get_global_x_pos(), get_global_y_pos(), Complex_2D::get_size_x(), Complex_2D::get_size_y(), MAG, nx, ny, object, parallel, single_result, singleCDI, weights, weights_set, x_position, and y_position.
int check_position (int n_probe, double step_size = 4, int min_x = -50, int max_x = 50, int min_y = -50, int max_y = 50, int tries = 0) [private]
A position alignment function. See `adjust_positions` above for more detail.
Parameters:
n_probe The index to the local frame which needs to be aligned
step_size Check the 8 positions located around the current positions using a step size of `step_size` pixels.
min_x The minimum distance horizontally, in pixel, for which the re-alignment will check.
max_x See min_x.
min_y See min_y.
max_y See max_y.
tries How many times has this function been called for this positions. After 10 tries the algorithm gives up and returns to the original position.
cout << `checking probe `<< n_probe << ` position, ` << x << `,` << y << ` with step size ` << step_size << `. Try no.: `<<tries<< endl;
if(n_probe==4&&new_x==3294&&new_y==2917){ static int h = 0; char blah[80]; Double_2D temp(1024,1024); single_result.at(n_probe)->get_2d(PHASE,temp); sprintf(blah,`single_prob%i_try%i.tiff`,n_probe,h); write_image(blah,temp,true,-0.1,0);
object->get_2d(PHASE,temp); sprintf(blah,`object_prob%i_try%i.tiff`,n_probe,h); write_image(blah,temp,true,-0.1,0);
h++;
cout << `error at (`<<new_x<<`,`<<new_y << `)`<<` is `<<single->get_error()<<endl;
}
cout << `moving probe `<< n_probe << ` by ` << x_position.at(n_probe)-x <<` in x ` << `and `<< y_position.at(n_probe)-y<<` in y.` << endl;
Definition at line 574 of file PhaseDiverseCDI.c++.
References add_to_object(), beta, Complex_2D::copy(), FAILURE, BaseCDI::get_error(), Complex_2D::get_size_x(), Complex_2D::get_size_y(), BaseCDI::iterate(), object, scale, set_result(), single_result, singleCDI, SUCCESS, update_from_object(), weights_set, x_position, and y_position.
int get_global_x_pos (int x, double x_offset) [inline, private]
Get the global pixel `x` coordinate using a local frame `x` and the frame offset.
Parameters:
x the local frame pixel position in x
x_offset the offset of the local frame with respect to the other frames.
Definition at line 441 of file PhaseDiverseCDI.h.
References x_min.
int get_global_y_pos (int y, double y_offset) [inline, private]
See get_global_x_pos
Definition at line 448 of file PhaseDiverseCDI.h.
References y_min.
int get_local_x_pos (int x, double x_offset) [inline, private]
See get_global_x_pos
Definition at line 455 of file PhaseDiverseCDI.h.
References x_min.
int get_local_y_pos (int y, double y_offset) [inline, private]
See get_global_x_pos
Definition at line 462 of file PhaseDiverseCDI.h.
References y_min.
Field Documentation
std::vector<Double_2D *> weights [protected]
A vector holding the weighting function for each frame
Definition at line 106 of file PhaseDiverseCDI.h.
Complex_2D* object [protected]
The current estimate of the 'global' sample function
Definition at line 120 of file PhaseDiverseCDI.h.
int iterations_per_cycle [protected]
The number of iterations to perform for each 'local' frame
Definition at line 123 of file PhaseDiverseCDI.h.
int scale [protected]
A factor which controls sub-pixel alignment. 1=regular, 2 = 2 'global' pixels for every 1 'local' pixel. i.e. 2 allows alignment to within half a pixel.
Definition at line 128 of file PhaseDiverseCDI.h.
int nx [protected]
The size in x and y of the 'global' sample function.
Definition at line 131 of file PhaseDiverseCDI.h.
int x_min [protected]
Minimum coordinates of the 'global' function based on the positions entered by the user.
Definition at line 135 of file PhaseDiverseCDI.h.
bool parallel [protected]
a flag for running in either series or parallel mode
Definition at line 139 of file PhaseDiverseCDI.h.
bool weights_set [protected]
a flag indicating whether the weights need to be recalculated
Definition at line 142 of file PhaseDiverseCDI.h.
The documentation for this class was generated from the following files:
PhaseDiverseCDI.h
PhaseDiverseCDI.c++