TransmissionConstraint Class Reference
An instance of this class will contain a description of any constraints which should be applied to the transmission function (FresnelCDI) or exit-surface-wave (PlanarCDI).
#include <TransmissionConstraint.h>
Public Member Functions
TransmissionConstraint ()
~TransmissionConstraint ()
void delete_complex_constraint_regions ()
virtual void add_complex_constraint (ComplexConstraint &new_constraint)
void set_charge_flipping (bool enable, int flip_sign=1)
void set_enforce_unity (bool enable)
void set_custom_constraint (void(*custom_constraint)(Complex_2D &transmission))
virtual void apply_constraint (Complex_2D &transmission)
Protected Attributes
std::vector< ComplexConstraint * > complex_constraint_list
Double_2D * region_map
bool do_enforce_unity
bool do_charge_flip
int flip_sign
void(* custom_constraint)(Complex_2D &)
Detailed Description
This class allows constraints on the transmission function (FresnelCDI) or exit-surface-wave (PlanarCDI), such as complex constraints to be used. To achieve this the user needs to:
create an instance of this class
configure it (for example by setting some ComplexConstraint objects
and finally by passing this object to the reconstruction (through the PlanarCDI or FresnelCDI function `set_complex_constraint`).
See also: the example `ComplexConstraints_example.c`.
Definition at line 225 of file TransmissionConstraint.h.
Constructor & Destructor Documentation
TransmissionConstraint ()
The constructor, no parameters need to be passed
Definition at line 25 of file TransmissionConstraint.c++.
References custom_constraint, region_map, set_charge_flipping(), and set_enforce_unity().
~TransmissionConstraint ()
The destructor
Definition at line 34 of file TransmissionConstraint.c++.
References region_map.
Member Function Documentation
void delete_complex_constraint_regions () [inline]
delete all the complex constraints associated with this TransmissionConstraint. Use with care!
Definition at line 262 of file TransmissionConstraint.h.
References complex_constraint_list, and region_map.
void add_complex_constraint (ComplexConstraint & new_constraint) [virtual]
A complex constraint. See ComplexConstraint for details of this class. Multiple regions can be defined by creating multiple ComplexConstraint objects, and by adding them one at a time using this function. All properties (other than the region) can be reset at any point during the reconstruction (i.e. after calling this function)
Parameters:
new_constraint The complex constraint to add.
Definition at line 40 of file TransmissionConstraint.c++.
References complex_constraint_list, ComplexConstraint::get_region(), and region_map.
void set_charge_flipping (bool enable, int flip_sign = 1) [inline]
Set whether charging flipping should or shouldn't be performed. i.e. unphysical phases will be changed from phi -> -phi. By default it will be performed. This function also allows the user to set the sign of the phases which should be flipped.
Parameters:
enable true - flipping is performed, false - it is not.
flip_sign The sign of the phase to flip. If the value passed is positive, all positive phases will be flipped to negative. If a negative value is passed, the converse is true.
Definition at line 299 of file TransmissionConstraint.h.
References do_charge_flip, and flip_sign.
void set_enforce_unity (bool enable) [inline]
Sets whether to enforce a unity constraint on the transmission magnitude. If true, magnitudes of the transmission function which are unphysical (above 1) will be reset to 1.
Parameters:
enable true - this constraint is applied, false - it is not.
Definition at line 314 of file TransmissionConstraint.h.
References do_enforce_unity.
void set_custom_constraint (void(*)(Complex_2D &transmission) custom_constraint) [inline]
It's not possible to write code for every situation in which someone wants to apply a constraint on the transmission function or exit-surface-wave. For this reason, this function is provided. It allows users to write their own custom constraint function and have it executed without the need to recompiled the main libraries of the software. The user's function must be of the form: void function_name(Complex_2D & array). Where 'array' is either the transmission function (FresnelCDI) or the exit-surface-wave (PlanarCDI). 'array' is passed to the function, and is also the return object (i.e. it is expected that the function will alter 'array').
It will be executed after the default constraints. To only have the user's function executed and no others, set this function and set set_charge_flipping(false) and set_enforce_unity(false).
Parameters:
custom_constraint A function pointer (the name of the function)
Definition at line 337 of file TransmissionConstraint.h.
void apply_constraint (Complex_2D & transmission) [virtual]
This is the function which is executed each time the support constraint is applied in Fresnel or Planar CDI reconstruction. The user should not generally need to use this function. An exception would be if no constraint is applied during reconstruction, but some general clean-up is required on the final Transmission function. For example, applying the unity constraint.
Before applying any constraints, the mean values of c=beta/delta will be calculated for each region defined through ComplexConstraint objects. The mean is calculated as:
 \bar{C} = \frac{\sum{lnA}}{\sum{\phi}} 
Where A is the transmission function amplitude, $ \phi $ is the phase and the summation runs over all values in the transmission function array for the defined region.
The constraints will be executed in the following order: - any complex constraints which have been passed to the object - charge flipping is performed - unity of the transmission function is enforced - custom constraints are applied.
now we start the main loop to alter the values in the transmission function array
Definition at line 79 of file TransmissionConstraint.c++.
References complex_constraint_list, custom_constraint, do_charge_flip, do_enforce_unity, flip_sign, Complex_2D::get_imag(), Complex_2D::get_mag(), ComplexConstraint::get_new_mag(), ComplexConstraint::get_new_phase(), Complex_2D::get_phase(), Complex_2D::get_size_x(), Complex_2D::get_size_y(), region_map, ComplexConstraint::set_c_mean(), Complex_2D::set_imag(), Complex_2D::set_mag(), and Complex_2D::set_phase().
Field Documentation
std::vector<ComplexConstraint*> complex_constraint_list [protected]
a list of the complex_constraints
Definition at line 230 of file TransmissionConstraint.h.
Double_2D* region_map [protected]
an array which hold the mapping between pixel and complex constraint
Definition at line 234 of file TransmissionConstraint.h.
bool do_enforce_unity [protected]
flag for whether unity on the transmission magnitude should be enforced
Definition at line 238 of file TransmissionConstraint.h.
bool do_charge_flip [protected]
flag for whether phase flipping should be enforced
Definition at line 241 of file TransmissionConstraint.h.
int flip_sign [protected]
the sign of the phase (+1, -1) to be flipped
Definition at line 244 of file TransmissionConstraint.h.
void(* custom_constraint)(Complex_2D &) [protected]
a function pointer to a cumstomized constraint
The documentation for this class was generated from the following files:
TransmissionConstraint.h
TransmissionConstraint.c++