ComplexConstraints_example.c File Reference
#include <iostream>
#include <sstream>
#include <stdlib.h>
#include <io.h>
#include <TransmissionConstraint.h>
#include <Complex_2D.h>
#include <Double_2D.h>
#include <FresnelCDI.h>
#include <cstdlib>
#include <cmath>
#include <cstring>
Functions
void my_charge_flipping (Complex_2D &transmission)
int main (int argc, char *argv[])
Detailed Description
This example aims at demonstrating how complex costraints can be inforced during a reconstruction. The example requires that FresnelCDI_WF_example.exe and FresnelCDI_simulation_example.c have been previously run.
Here, the complex constraint is apply to the transmission function during Fresnel reconstruction, but constraints such as charge flipping can be achieve in the same way on th exit-surface wave for plane-wave reconstruction.
Author: Nadia Davidson <nadiamd@unimelb.edu.au>
Last modified on 25/3/2011
Definition in file ComplexConstraints_example.c.
Function Documentation
int main (int argc, char * argv[])
Definition at line 68 of file ComplexConstraints_example.c.
References TransmissionConstraint::add_complex_constraint(), FresnelCDI::auto_set_norm(), Complex_2D::get_2d(), ComplexConstraint::get_c_mean(), BaseCDI::get_error(), FresnelCDI::get_transmission_function(), FresnelCDI::initialise_estimate(), BaseCDI::iterate(), MAG, my_charge_flipping(), PHASE, BaseCDI::set_algorithm(), TransmissionConstraint::set_charge_flipping(), BaseCDI::set_complex_constraint(), TransmissionConstraint::set_custom_constraint(), TransmissionConstraint::set_enforce_unity(), ComplexConstraint::set_fixed_c(), BaseCDI::set_intensity(), and BaseCDI::set_support().