FresnelCDI_simulation_example.c File Reference
#include <iostream>
#include <sstream>
#include <stdlib.h>
#include <io.h>
#include <Complex_2D.h>
#include <Double_2D.h>
#include <FresnelCDI.h>
#include <cstdlib>
#include <cmath>
#include <cstring>
#include <TransmissionConstraint.h>
Functions
int main (int argc, char *argv[])
Detailed Description
This file is a simulation of fCDI for the purpose of imaging small contrast changes in biological samples. It is based on Nadia's example and uses her header files. see: FresnelCDI_example.c
Author: Michael Jones <michael.jones@latrobe.edu.au>, Nadia Davidson <nadiamd@unimelb.edu.au>
Last modified on 18/3/2011
Definition in file FresnelCDI_simulation_example.c.
Function Documentation
int main (int argc, char * argv[])
Definition at line 39 of file FresnelCDI_simulation_example.c.
References Complex_2D::get_2d(), BaseCDI::get_error(), FresnelCDI::get_transmission_function(), FresnelCDI::initialise_estimate(), BaseCDI::iterate(), MAG, MAG_SQ, Complex_2D::multiply(), PHASE, FresnelCDI::propagate_from_detector(), FresnelCDI::propagate_to_detector(), BaseCDI::set_algorithm(), TransmissionConstraint::set_charge_flipping(), TransmissionConstraint::set_enforce_unity(), BaseCDI::set_intensity(), BaseCDI::set_support(), and Complex_2D::set_value().